### ISSUE TITLE
Memory leak when using MOSEK

### ISSUE THREAD

**Issue by itakatz** [cvxopt/cvxopt#101]
When I call the linear program method `solvers.lp` many times in my program with the MOSEK solver. The memory allocation grow with each call untill (if called enough times) the whole RAM of the machine is taken. 

I've added the following calls at the end of `solvers.lp` (in `msk.py` file):
```
task.__del__()
env.__del__()
```
And it seems to solve the problem. 
I got the idea to try it from reading here, section 6.2.1:
http://docs.mosek.com/8.0/pythonapi/guidelines.html

**Comment by martinandersen** [comment]
Thanks for pointing this out—we will look into this.

**Comment by aszekMosek** [comment]
It should be sufficient to use ``env`` and ``task`` in a ``with`` statement
