### ISSUE TITLE
suitesparse 4.5.3 or 4.5.4?

### ISSUE THREAD

**Issue by roversch** [cvxopt/cvxopt#102]
The newest version of suitesparse on conda-forge is `4.5.4`. However, CVXOPT seems to link to `4.5.3` and throws a dynamic linker error (coming from `cholmod`) because it cannot find version `4.5.3` of suitesparse, only version `4.5.4` is installed.

I had to reinstall suitesparse as follows: `conda install -c conda-forge suitesparse==4.5.3`, which fixed the issue. Could you check if the dependencies are set correctly and (eventually) update to `suitesparse4.5.4`?

**Comment by martinandersen** [comment]
The suitesparse dependency is specified as `suitesparse 4.5.*`, so I am actually not sure why it is not working. We'll look into this.

**Comment by martinandersen** [comment]
My guess is that this is related to conda-forge/suitesparse-feedstock#22.

**Comment by roversch** [comment]
Absolutely! Thanks for looking that up. You may close the issue, as it totally depends on them to fix that.

**Comment by martinandersen** [comment]
Suitesparse is now pinned to version 4.5.4 to avoid the install_name issue.
