### ISSUE TITLE
Inconsistent type for convert_num()

### ISSUE THREAD

**Issue by sebastien-villemot** [cvxopt/cvxopt#105]
This is [Debian bug #744955](https://bugs.debian.org/744955):

The last argument of function `convert_num()` is declared in `src/C/base.c` to be an `int`.
But in `src/C/dense.c` and `src/C/sparse.c`, the very same argument is declared to be an `int_t`.

This can create undefined behavior or crashes on platforms where `int` and `Py_ssize_t` have different bit width.

Cheers,

**Comment by martinandersen** [comment]
Thanks for pointing this out, we'll look into it.
