### ISSUE TITLE
Restricting variable types to binary and speed concerns with dense matrices

### ISSUE THREAD

**Issue by tbrailov** [cvxopt/cvxopt#106]
Hello, 

I have a quadratic programming problem as defined here:
![screen shot 2017-09-01 at 1 05 39 pm](https://user-images.githubusercontent.com/29532792/29985981-4b423176-8f16-11e7-9132-828537a25357.png)
(from this paper: http://www.sciencedirect.com/science/article/pii/S0377221706004759) 

I would like to use your package to solve this problem, however I am not sure how to enforce the constraint that x_i are supposed to be 0 or 1.

Additionally I have a speed concern with my problem. The weight matrix Q as in the screenshot is 113x113 and the only 0 entries are on the diagonal. I am wondering if this can be handled efficiently by your package, since all the sample uses in the docs have much smaller matrices. 

Thanks,
Tatiana

**Comment by martinandersen** [comment]
CVXOPT is for convex optimization, and hence it cannot handle binary variables. However, you can solve a convex relaxation of the problem with CVXOPT (e.g., an SDP relaxation).
