### ISSUE TITLE
Install leaves an empty '${PREFIX}/cvxopt' directory

### ISSUE THREAD

**Issue by yurivict** [cvxopt/cvxopt#111]
Please remove it.

**Comment by martinandersen** [comment]
How did you install the package?

**Comment by yurivict** [comment]
> How did you install the package?

Using the FreeBSD port math/py-cvxopt.
Found the problem while creating it.

**Comment by martinandersen** [comment]
I'm not sure I understand the problem. There is nothing in setup.py that explicitly creates that directory, so I don't see how this is related to CVXOPT?

**Comment by martinandersen** [comment]
We believe this is not related to CVXOPT; please reopen if you disagree.
