### ISSUE TITLE
Please publish the list of dependencies

### ISSUE THREAD

**Issue by yurivict** [cvxopt/cvxopt#112]
It is usually in setup.py of requirements.txt.

Also you depend on something called "mosek". It is closed source. I can't install closed source on FreeBSD. Does this mean that cvxopt is unusable for me?

**Comment by martinandersen** [comment]
CVXOPT does not depend on any Python packages, but it requires some external libraries (BLAS, LAPACK, and SuiteSparse) to build CVXOPT from source (please see the [installation instructions](http://cvxopt.org/install/index.html) for details). MOSEK is not a requirement; it can be used if it is available.
