### ISSUE TITLE
ValueError: Rank(A) < p or Rank([G; A]) < n

### ISSUE THREAD

**Issue by moakra** [cvxopt/cvxopt#113]
Hi,

I am trying to solve a linear program:
min **c**.T x    subject to   **A** **x** < 0

with random iid Gaussian c and A. The code is as follows:

mu, sigma2 = 0, 10
constraints_nbr, dim = 1, 100

A = np.sqrt(sigma2) * np.random.randn(constraints_nbr, dim) + mu
A_mtx = * matrix(A)

c = np.sqrt(sigma2) * np.random.randn(1, dim) + mu
c_mtx = * matrix(c.T)

b = np.zeros((constraints_nbr, 1))
b_mtx = 1.0 * matrix(b)

x_star =  solvers.lp(c_mtx,A_mtx,b_mtx)['x']

I am still getting: ValueError: Rank(A) < p or Rank([G; A]) < n

Any idea why I have this error ?

Thanks!

**Comment by martinandersen** [comment]
Your problem does not satisfy the rank requirement described in the [user's guide](http://cvxopt.org/userguide/coneprog.html#linear-cone-programs). 

The problem can be solved analytically: it is unbounded below unless A'*z = -c for some z >= 0 (in which case the dual problem is feasible).

**Comment by ShubhankarKapoor** [comment]
Hi,

I checked the ranks of the matrices and it does tend to satisfy the ranking criteria where rank(A)=p and rank ([P; G; A]) = n. I was wondering if that is the problem or if there could be any other potential issues.

Cheers

**Comment by ashish010** [comment]
It might be because of the numpy.random function you're using. Try playing with the function by adding different values. For e.g. np.random.radn(0)
