### ISSUE TITLE
Support for OSX 10.11

### ISSUE THREAD

**Issue by galbramc** [cvxopt/cvxopt#117]
The latest release of cvxopt does not work on OSX 10.11:

```
Traceback (most recent call last):
  File "/Users/jenkins/workspace/gpkit_Install/buildnode/macys_VM/venv2_gpkit/lib/python2.7/site-packages/gpkit/tests/t_model.py", line 548, in test_cvxopt_kwargs
    sol = m.solve(solver="cvxopt", verbosity=0, kktsolver="ldl")
  File "/Users/jenkins/workspace/gpkit_Install/buildnode/macys_VM/venv2_gpkit/lib/python2.7/site-packages/gpkit/constraints/prog_factories.py", line 80, in solvefn
    result = progsolve(solver, verbosity, **kwargs)
  File "/Users/jenkins/workspace/gpkit_Install/buildnode/macys_VM/venv2_gpkit/lib/python2.7/site-packages/gpkit/constraints/gp.py", line 164, in solve
    solverfn, solvername = _get_solver(solver)
  File "/Users/jenkins/workspace/gpkit_Install/buildnode/macys_VM/venv2_gpkit/lib/python2.7/site-packages/gpkit/constraints/gp.py", line 149, in _get_solver
    from .._cvxopt import cvxoptimize
  File "/Users/jenkins/workspace/gpkit_Install/buildnode/macys_VM/venv2_gpkit/lib/python2.7/site-packages/gpkit/_cvxopt.py", line 2, in <module>
    from cvxopt import spmatrix, matrix, log
  File "/Users/jenkins/workspace/gpkit_Install/buildnode/macys_VM/venv2_gpkit/lib/python2.7/site-packages/cvxopt/__init__.py", line 50, in <module>
    import cvxopt.base
ImportError: dlopen(/Users/jenkins/workspace/gpkit_Install/buildnode/macys_VM/venv2_gpkit/lib/python2.7/site-packages/cvxopt/base.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Users/jenkins/workspace/gpkit_Install/buildnode/macys_VM/venv2_gpkit/lib/python2.7/site-packages/cvxopt/.dylibs/libgfortran.4.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/jenkins/workspace/gpkit_Install/buildnode/macys_VM/venv2_gpkit/lib/python2.7/site-packages/cvxopt/.dylibs/libgfortran.4.dylib
```

I believe that Apple still supports 10.11. Could it be possible to compiled libgfortran with at least 10.11 compatibility, preferably 10.10? I can help compiling it if you would like me to. You can also likely get it from homebrew.

**Comment by martinandersen** [comment]
Thanks for reporting this, I'll look into it. The wheels are being built here: [cvxopt-wheels](https://github.com/cvxopt/cvxopt-wheels). The macOS wheels are based on homebrew packages, but perhaps choosing a different osx image would solve this problem?

**Comment by martinandersen** [comment]
I think it may be related to Travis CI switching to a new [default osx image](https://blog.travis-ci.com/2017-10-16-a-new-default-os-x-image-is-coming).

**Comment by galbramc** [comment]
I'm not sure it's the travis update. They say they went from 10.12.5 to 10.12.6. The error is related to libSystem.B.dylib which is a system library. If you can choose a 10.11 image to compile the wheel that should fix it.

**Comment by galbramc** [comment]
Yeah that would do it. I know homebrew has precompiled bottles going back to 10.11, but if you can go back to 10.10 that would be great. I've seen various software these days have 10.10 as the minimum version (something significant seems to have changed). We often deal with organizations that are slow to upgrade operating systems.

**Comment by martinandersen** [comment]
I'm rebuilding with the xcode6.4 image which is the only 10.10 image.

**Comment by galbramc** [comment]
Sounds great! Thank you so much for resolving this so quickly.

**Comment by martinandersen** [comment]
That seems to work. @galbramc would you be able to test it?

[cvxopt-1.2.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl](https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com/cvxopt-1.2.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl)

**Comment by martinandersen** [comment]
Never mind, there is an issue on 10.12. I'll keep you posted.

**Comment by galbramc** [comment]
Yeah I got an error on 10.13 as well.

```
python -c "import cvxopt; print cvxopt.__version__"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/galbramc/venv/lib/python2.7/site-packages/cvxopt/__init__.py", line 279, in <module>
    from cvxopt import solvers, blas, lapack
ImportError: dlopen(/Users/galbramc/venv/lib/python2.7/site-packages/cvxopt/lapack.so, 2): Symbol not found: _dgesv_
  Referenced from: /Users/galbramc/venv/lib/python2.7/site-packages/cvxopt/lapack.so
  Expected in: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
 in /Users/galbramc/venv/lib/python2.7/site-packages/cvxopt/lapack.so
```

**Comment by martinandersen** [comment]
It works on 10.13 with `osx_image: xcode7.3` (which corresponds to 10.11). Could you try this one? 

The most recent wheels are available in this [Rackspace container](https://3f23b170c54c2533c070-1c8a9b3114517dc5fe17b7c3f8c63a43.ssl.cf2.rackcdn.com).

**Comment by galbramc** [comment]
I'm not sure I grabbed the right wheels. This is on 10.13. Did I miss something?

```
pip install cvxopt-1.2.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl 
cvxopt-1.2.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl is not a supported wheel on this platform.

pip install cvxopt-1.2.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl 
cvxopt-1.2.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl is not a supported wheel on this platform.

pip install cvxopt-1.2.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl 
cvxopt-1.2.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl is not a supported wheel on this platform.
```

**Comment by galbramc** [comment]
Everything seems to be working through pip as well. Thank you for all your help. Feel free to go ahead and close this issue.

**Comment by martinandersen** [comment]
OK, thanks. I just added the new versions to pypi. Thanks for reporting this.
