### ISSUE TITLE
Kernel died, restarting issue

### ISSUE THREAD

**Issue by arvinarvi** [cvxopt/cvxopt#119]
When _Q = 2*matrix([[2, .5], [.5, 1]])_ is executed, _Kernel died, restarting_ error is encountered. (Ubuntu 16.04, installed cvxopt through anaconda). Kindly let me know the solution.

**Comment by martinandersen** [comment]
Which version of Python/CVXOPT are you using?

```
python --version
conda list cvxopt
```

**Comment by martinandersen** [comment]
Also, does the following work without any errors?

```
python -c 'from cvxopt import matrix; Q = 2*matrix([[2, .5], [.5, 1]]); print(Q)'
```

**Comment by arvinarvi** [comment]
Python 3.6.1
cvxopt 1.1.8
Executing the command, I get the following error

_Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so._

**Comment by martinandersen** [comment]
I believe that you are using an old conda package that we didn't create (and hence do not support). I would suggest that you reinstall `cvxopt` from the conda-forge channel:

```
conda install -c conda-forge cvxopt
```

**Comment by arvinarvi** [comment]
Thanks for your prompt reply. Its working fine now.
