### ISSUE TITLE
decrementing count of unowned reference

### ISSUE THREAD

**Issue by slivingston** [cvxopt/cvxopt#120]
## Summary

Pull request #116 introduced a code path that leads to decrementing the count of a borrowed reference, which can result in a segmentation fault.

## Minimal demonstrating example

Consider [examples/book/chap7/maxent.py](https://github.com/cvxopt/cvxopt/blob/fde955b6e63ffd84dad41d0ab2456cdd5b54c9c2/examples/book/chap7/maxent.py) in the sourcetree. Providing that CVXOPT is built with support for GLPK, patch the example code:

```diff
diff --git a/examples/book/chap7/maxent.py b/examples/book/chap7/maxent.py
index ca0736f..1a48244 100755
--- a/examples/book/chap7/maxent.py
+++ b/examples/book/chap7/maxent.py
@@ -3,6 +3,7 @@
 import functools
 
 from cvxopt import solvers, blas, matrix, spmatrix, spdiag, log, div
+solvers.options['glpk'] = dict(msg_lev='GLP_MSG_OFF')
 #solvers.options['show_progress'] = False
 
 # minimize     p'*log p  
@@ -68,8 +69,8 @@ GG[n::n+9] = -1.0
 hh = matrix(0.0, (n+8,n))
 hh[:n,:] = matrix([i>=j for i in range(n) for j in range(n)], 
     (n,n), 'd')  # upper triangular matrix of ones
-l = [-blas.dot(cc, solvers.lp(cc, GG, hh[:,k])['x']) for k in range(n)]
-u = [blas.dot(cc, solvers.lp(cc, GG, -hh[:,k])['x']) for k in range(n)]
+l = [-blas.dot(cc, solvers.lp(cc, GG, hh[:,k], solver='glpk')['x']) for k in range(n)]
+u = [blas.dot(cc, solvers.lp(cc, GG, -hh[:,k], solver='glpk')['x']) for k in range(n)]
 
 def f(x,y): return x+2*[y]
 def stepl(x): return functools.reduce(f, x[1:], [x[0]])
```

Then,

    python examples/book/chap7/maxent.py

This should end in segmentation fault.

## Discussion

When the `options` keyword argument is provided to the glpk simplex() function, `opts` is assigned to `param` ([line 212 of glpk.c](https://github.com/cvxopt/cvxopt/blob/fde955b6e63ffd84dad41d0ab2456cdd5b54c9c2/src/C/glpk.c#L212)). However, the reference `opts` as obtained from [PyArg_ParseTupleAndKeywords](https://docs.python.org/3.5/c-api/arg.html#c.PyArg_ParseTupleAndKeywords) is borrowed, as noted in [the Python/C API documentation](https://docs.python.org/3.5/c-api/arg.html):

> Note that any Python object references which are provided to the caller are borrowed references; do not decrement their reference count!

The error thus occurs in this case at `Py_DECREF(param)` on [line 358 of glpk.c](https://github.com/cvxopt/cvxopt/blob/fde955b6e63ffd84dad41d0ab2456cdd5b54c9c2/src/C/glpk.c#L358).

When the `options` keyword argument is not provided, `param` is assigned the `options` dictionary of the module ([line 214 of glpk.c](https://github.com/cvxopt/cvxopt/blob/fde955b6e63ffd84dad41d0ab2456cdd5b54c9c2/src/C/glpk.c#L214)) using PyObject_GetAttrString, which [provides a new reference](https://docs.python.org/3.5/c-api/object.html#c.PyObject_GetAttrString), so it is safe (and best) to call `Py_DECREF` later.

The above example only demonstrates the bug for simplex() in glpk.c, but because the same idiom was used in other places in commit a71a79d02e429c6725b289287642dbf8dcb591ea (from pull request #116), it is worth checking the other solvers.

**Comment by slivingston** [comment]
In terms of solutions, I think that it suffices to
```diff
diff --git a/src/C/glpk.c b/src/C/glpk.c
index b9feef8..d22e4db 100644
--- a/src/C/glpk.c
+++ b/src/C/glpk.c
@@ -355,7 +355,9 @@ static PyObject *simplex(PyObject *self, PyObject *args, PyObject *kwrds)
             }
         }
 
-    Py_DECREF(param);
+    /* only decrement the count if we own the reference: if param is not opts */
+    if (param != opts)
+        Py_DECREF(param);
 
     switch (glp_simplex(lp, &smcp)){
```

**Comment by martinandersen** [comment]
Thanks for reporting this—we will fix this as soon as possible.
