### ISSUE TITLE
Double free or corruption with CVXOPT 1.2.0

### ISSUE THREAD

**Issue by stephane-caron** [cvxopt/cvxopt#123]
I have a problem with the following LP example with ``cvxopt==1.2.0``:
```python
import numpy, cvxopt, cvxopt.solvers

cvxopt.solvers.options['glpk'] = {'msg_lev': 'GLP_MSG_OFF'}  # used to work with cvxopt 1.1.8

def cvxopt_solve_lp(c, G, h):
    args = [cvxopt.matrix(c), cvxopt.matrix(G), cvxopt.matrix(h)]
    sol = cvxopt.solvers.lp(*args, solver='glpk')
    return numpy.array(sol['x']).reshape((c.shape[0],))

c, G, h = -numpy.ones(10), numpy.eye(10), numpy.zeros(10)
problems = [(c, G, h)] * 2
for i, (c, G, h) in enumerate(problems):
    x = cvxopt_solve_lp(c, G, h)
    print "LP %d:" % i, x
```

When I run it, the first LP goes fine but the second yields a "double free or corruption" error:
```bash
$ python cvxopt_debug.py                                                               134 ↵
LP 0: [-0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
GLPK Simplex Optimizer, v4.52
10 rows, 10 columns, 10 non-zeros
*     0: obj =   0.000000000e+00  infeas =  0.000e+00 (0)
*    10: obj =   0.000000000e+00  infeas =  0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
*** Error in `python': double free or corruption (!prev): 0x00000000010ad7e0 ***
[1]    6857 abort (core dumped)  python cvxopt_debug.py
```

**Observations:**
- my OS is Ubuntu 14.04, so the Python above is 2.7.6
- no error with ``cvxopt==1.1.9``
- error only occurs when there is more than one problem in ``problems``
- error disappears when commenting out the ``'msg_lev'`` GLPK option
- error disappears when inlining the body of the function inside the for loop

**Bonus question:** what's the new syntax to turn of GLPK's terminal output?

**Comment by martinandersen** [comment]
Thanks for reporting this. I can reproduce the error on macOS. It appears to be a bug related to global options—we'll provide a fix. In the meantime you can pass options as a keyword argument:

```
sol = cvxopt.solvers.lp(*args, solver='glpk', options={'glpk':{'msg_lev': 'GLP_MSG_OFF'}})
```

**Comment by martinandersen** [comment]
This is the same issue as #120
