### ISSUE TITLE
fail to install cvxopt on  Jetson

### ISSUE THREAD

**Issue by caserzer** [cvxopt/cvxopt#125]
I try to install cvxopt on  Jetson TX2 (JetPack 3.2 ubuntu 16.04) but failed.
I already install libsuitesparse-dev by sudo apt-get install libsuitesparse-dev .
I tried to install the cvxopt by sudo pip3 install cvxop and got these error
 
```
 building 'umfpack' extension
    aarch64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.5m -c src/C/umfpack.c -o build/temp.linux-aarch64-3.5/src/C/umfpack.o
    src/C/umfpack.c:23:21: fatal error: umfpack.h: No such file or directory
    compilation terminated.
    error: command 'aarch64-linux-gnu-gcc' failed with exit status 1
```
I check that the umfpack.h exist in the /usr/include/suitesparse

**Comment by martinandersen** [comment]
You probably need to specify where the header file is located:

Try the following:

```
CVXOPT_SUITESPARSE_INC_DIR=/usr/include/suitesparse pip3 install cvxopt
```


Here's the relevant part of the installation instructions:

> - `SUITESPARSE_LIB_DIR`: the directory containing SuiteSparse libraries.
> - `SUITESPARSE_INC_DIR`: the directory containing SuiteSparse header files.
> - `SUITESPARSE_SRC_DIR`: the directory containing SuiteSparse source. The variables `SUITESPARSE_LIB_DIR` and `SUITESPARSE_INC_DIR` are ignored and relevant parts of SuiteSparse are build from source when `SUITESPARSE_SRC_DIR` is specified.
> 
> Each of the variables can be overridden by specifying an environment variable with the prefix `CVXOPT_`.

Alternatively, download the SuiteSparse source and set `CVXOPT_SUITESPARSE_SRC_DIR` before building CVXOPT:

```
wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-5.2.0.tar.gz
tar -xf SuiteSparse-5.2.0.tar.gz
export CVXOPT_SUITESPARSE_SRC_DIR=$(pwd)/SuiteSparse
```

**Comment by caserzer** [comment]
thanks @martinandersen. It works
