### ISSUE TITLE
ValueError: domain error

### ISSUE THREAD

**Issue by ShubhankarKapoor** [cvxopt/cvxopt#133]
Hi,

site-packages\cvxopt\misc.py", line 450, in update_scaling
    s[:m] = base.sqrt( s[:m] )

Though this error has been previously addressed by changing the parameters of the qp solver or by normalizing the data, I have tried those variants but I still get this error.

I was hoping for some suggestions.

Thanks,
Shubhankar

**Comment by martinandersen** [comment]
Do you have a minimal example that reproduces the problem? It is impossible to find out what is wrong without an example.

**Comment by ShubhankarKapoor** [comment]
Hi thanks for the reply and many apologies, there was a sign error in the paper. It all worked at the end.

**Comment by M4ROs** [comment]
> Hi thanks for the reply and many apologies, there was a sign error in the paper. It all worked at the end.

Hi, I found your previous question - https://github.com/cvxopt/cvxopt/issues/50. I am probably solving same problem, with same data and found same error. Can you please tell, where there was a problem? How did you solved it.

Many thanks,

Maroš
