### ISSUE TITLE
cvxopt.solvers.qp doesnt work

### ISSUE THREAD

**Issue by mungsoo** [cvxopt/cvxopt#134]
I call this function and get an error.
`   raise ValueError("Rank(A) < p or Rank([P; A; G]) < n")
ValueError: Rank(A) < p or Rank([P; A; G]) < n`

I m using 1.2.2. After trying for the whole day, I give up and use quadprog. And it works... I do not modify any code. Is there anything wrong with cvxopt?

**Comment by martinandersen** [comment]
As mentioned in the documentation, `qp` is an interface to `coneqp`, and if you read the `coneqp`  [documentation](http://cvxopt.org/userguide/coneprog.html#cvxopt.solvers.coneqp), you'll see that the rank condition that you see in the error message is required to hold. 

Ref: #90, #95, #113
