### ISSUE TITLE
Is it possible to constrain a large sparse matrix to be PSD?

### ISSUE THREAD

**Issue by alecjacobson** [cvxopt/cvxopt#136]
Specifically my problem looks like this:

min || X - Y * L *B ||_F^2
L, z
subject to L >= 0   // L is positive semidefinite 
AND L = sparse( i , j , z)  // L is a sparse matrix with non-zeros at known subscripts (i,j) and unknown values z 

Can this be modelled as problem that cvxopt can solve efficiently?

**Comment by martinandersen** [comment]
Yes, you can model this as either a cone LP or a cone QP, but the question of efficiency depends on the problem dimensions.

**Comment by alecjacobson** [comment]
Let's say L is 100,000 by 100,000 but has <100 non-zeros per row.

**Comment by martinandersen** [comment]
This is most likely too big for a general-purpose interior-point method.

**Comment by alecjacobson** [comment]
Is it because L will be treated as dense?

>

**Comment by martinandersen** [comment]
Yes, generally speaking, a general-purpose IPM will treat L as dense. You can use the conversion method of [Fukuda et al. (2000)](http://doi.org/10.1137/S1052623400366218) to turn the problem into an equivalent block-diagonal SDP, but this is only useful if the sparsity graph associated with L has a small tree width such that the blocks are small.

**Comment by alecjacobson** [comment]
Thank you for the quick responses. Is the same true for smcp https://github.com/cvxopt/smcp/issues/10 (happy to merge the discussion or keep them separate).

**Comment by martinandersen** [comment]
SMCP will represent L as a sparse matrix, but the number of constraints required to express your problem in the required form will probably make it too expensive to solve with SMCP anyway.
