### ISSUE TITLE
Impossible to fix certain values in matrix variables

### ISSUE THREAD

**Issue by cyrilgarcia009** [cvxopt/cvxopt#140]
<img width="830" alt="screenshot 2019-02-25 at 23 16 44" src="https://user-images.githubusercontent.com/20226693/53423121-c264f600-39ae-11e9-920b-72aa11ebb258.png">

I looked at different websites and requests but I couldn't find how to code such a constraint where some elements of the matrix are kept constant (see photo attached). Does anyone know if this is possible using CVXOPT? Thank you for your help!

**Comment by martinandersen** [comment]
Yes, it is possible. You can express this as an LMI or as a set of equality constraints and a positive semidefinite matrix constraint. Take a look at the examples in the user guide. You can also use CVXPY to set up the problem if you prefer to use a high-level modeling language.

**Comment by cyrilgarcia009** [comment]
Yes, I understand, thank you for your reply. The issue here is that I didn't find how to create a variable which depends on another one in CVXPY despite a long time spent looking for such an answer. In this case, I can't find how to define a matrix whose coefficients depends on variables and constants. Thank you for your help!

**Comment by martinandersen** [comment]
Take a look at the example in the follows section of the documentation: 
http://cvxopt.org/userguide/coneprog.html#semidefinite-programming 

Scroll down to the part that says "*We illustrate the calling sequence with a small example*".
