### ISSUE TITLE
Directly give matrix arguments for SDPs

### ISSUE THREAD

**Issue by vijay092** [cvxopt/cvxopt#159]
Hi!

I have only started using cvxopt today to solve an SDP. I was wondering if we could directly give matrix arguments to cvxopt the way we do in CVX (MATLAB)?
In particular, I just want to define it as X >= 0 rather than x0[1 0;0 0] + x1[0 1;1 0] + x2[0 0;0 1].

**Comment by martinandersen** [comment]
You can do that with modeling packages such as CVXPY and PICOS. Both of these can use CVXOPT as solver.
