### ISSUE TITLE
Missing windows wheel on python3.8

### ISSUE THREAD

**Issue by mtreinish** [cvxopt/cvxopt#161]
For the latest 1.2.4 release there are precompiled binary wheels uploaded to pypi for python 3.8 on mac osx and linux but not for windows: https://pypi.org/project/cvxopt/#files There are windows wheels for 2.7, 3.5, 3.6, and 3.7 but not 3.8. Would it be possible to build and push the missing wheel to pypi too?

**Comment by martinandersen** [comment]
Python 3.8 changes how DLL dependencies for extension modules are resolved, so unfortunately there is no quick solution, I think. The [cvxopt/cvxopt-wheels](https://github.com/cvxopt/cvxopt-wheels) repo is where we build wheels, including wheels for Windows via AppVeyor — we welcome PRs that address #127 and/or this issue. In the meantime, a Windows version of CVXOPT for Python 3.8 is available through [conda-forge/cvxopt-feedstock](https://github.com/conda-forge/cvxopt-feedstock).

**Comment by martinandersen** [comment]
We now have Windows wheels (x86 and x64) for Python 3.5-3.8 with OpenBLAS. Wheels for Python 3.9 will be available once AppVeyor adds support for Python 3.9.
