### ISSUE TITLE
Spline LS typo

### ISSUE THREAD

**Issue by rileypeterson** [cvxopt/cvxopt#162]
I'm trying to learn/understand convex optimization and this package so I've been going through the examples. I was looking [here](https://github.com/cvxopt/cvxopt/blob/master/examples/book/chap6/polapprox.py#L104-L113). I've been trying to figure out why `G'` isn't included in the `K` matrix... and now I'm convinced it's just a typo. 

Should be:
```python
K = matrix(0.0, (n+6,n+6))
K[:n,:n] = A.T * A
K[n:,:n] = G
K[:n,n:] = G.T # <---- add G' contribution
xls = matrix(0.0, (n+6,1))
xls[:n] = A.T * y
lapack.sysv(K, xls)
xls = xls[:n]
```

Is this right? I'm trying to check my understanding, regardless, it has no effect on the solution.

**Comment by martinandersen** [comment]
It is intentional: only the lower triangular part of the symmetric matrix K is required to solve the system using LAPACK's [DSYSV](http://www.netlib.org/lapack/explore-html/d3/d77/dsysv_8f.html) routine. The upper triangular part is never accessed.
