### ISSUE TITLE
number of elements exceeds INT_MAX

### ISSUE THREAD

**Issue by lizhijie-sitx** [cvxopt/cvxopt#169]
Hi,

When I use **cvxopt.solvers.sdp** to deal with big matrix input. It raise a exception:

`OverflowError: number of elements exceeds INT_MAX`

I find the code in dense.c

```
/*
  Creates an unpopulated "empty" matrix. In API
 */
matrix * Matrix_New(int nrows, int ncols, int id)
{
  matrix *a;
  if ((nrows < 0) || (ncols < 0) || (id < INT) || (id > COMPLEX)) {
    PyErr_BadInternalCall();
    return NULL;
  }
  else if (ncols > 0 && nrows > (INT_MAX/ncols)) {
    PyErr_SetString(PyExc_OverflowError, "number of elements exceeds INT_MAX");
    return NULL;
  }
  else if (!(a = (matrix *)matrix_tp.tp_alloc(&matrix_tp, 0))) {
    PyErr_NoMemory();
    return NULL;
  }

  a->id = id; a->nrows = nrows; a->ncols = ncols;
  if ((a->buffer = calloc(nrows*ncols,E_SIZE[id])))
    return a;
  else if (nrows*ncols == 0) 
    return a;
  else {
#if PY_MAJOR_VERSION >= 3
    Py_TYPE(a)->tp_free((PyObject*)a);
#else
    a->ob_type->tp_free((PyObject*)a);
#endif
    return (matrix *)PyErr_NoMemory();
  }
}
```

I don't know why set the INT_MAX limit here. Is it easy to support matrix elements exceeds INT_MAX?

**Comment by lizhijie-sitx** [comment]
I find the previous issue #126
I'm using the latest code. Is there any plan to support large scale matrix ?

**Comment by martinandersen** [comment]
As mentioned in #126:
>  Accommodating the ILP64 version of BLAS/LAPACK will require significant changes. This is something that we would like to do eventually, but it will probably not happen any time soon.
