### ISSUE TITLE
Installation error with pip, Python 3.7.5, Windows 10

### ISSUE THREAD

**Issue by arbitrager44** [cvxopt/cvxopt#175]
Running a simple `pip install cvxopt` I get a series of errors:

>Collecting cvxopt
  Using cached cvxopt-1.2.5.tar.gz (6.7 MB)
Building wheels for collected packages: cvxopt
  Building wheel for cvxopt (setup.py) ... error
  ERROR: Command errored out with exit status 1:

At which point it attempts to install using setup.py, according to this part of the error:
>DEPRECATION: Could not build wheels for cvxopt which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.

That attempt then produces this error:
> ERROR: Command errored out with exit status 1:
     command: 'c:\users\arbit\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\arbit\\AppData\\Local\\Temp\\pip-install-s6rs24i8\\cvxopt\\setup.py'"'"'; __file__='"'"'C:\\Users\\arbit\\AppData\\Local\\Temp\\pip-install-s6rs24i8\\cvxopt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\arbit\AppData\Local\Temp\pip-record-lzcs604f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\arbit\appdata\local\programs\python\python37-32\Include\cvxopt'
         cwd: C:\Users\arbit\AppData\Local\Temp\pip-install-s6rs24i8\cvxopt\
    Complete output (33 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.7
    creating build\lib.win32-3.7\cvxopt
    copying src\python\coneprog.py -> build\lib.win32-3.7\cvxopt
    copying src\python\cvxprog.py -> build\lib.win32-3.7\cvxopt
    copying src\python\info.py -> build\lib.win32-3.7\cvxopt
    copying src\python\misc.py -> build\lib.win32-3.7\cvxopt
    copying src\python\modeling.py -> build\lib.win32-3.7\cvxopt
    copying src\python\msk.py -> build\lib.win32-3.7\cvxopt
    copying src\python\printing.py -> build\lib.win32-3.7\cvxopt
    copying src\python\solvers.py -> build\lib.win32-3.7\cvxopt
    copying src\python\_version.py -> build\lib.win32-3.7\cvxopt
    copying src\python\__init__.py -> build\lib.win32-3.7\cvxopt
    UPDATING build\lib.win32-3.7\cvxopt/_version.py
    set build\lib.win32-3.7\cvxopt/_version.py to '1.2.5'
    running build_ext
    building 'base' extension
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    creating build\temp.win32-3.7\Release\src
    creating build\temp.win32-3.7\Release\src\C
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\arbit\appdata\local\programs\python\python37-32\include -Ic:\users\arbit\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/C/base.c /Fobuild\temp.win32-3.7\Release\src/C/base.obj
    base.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\arbit\appdata\local\programs\python\python37-32\include -Ic:\users\arbit\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/C/dense.c /Fobuild\temp.win32-3.7\Release\src/C/dense.obj
    dense.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\arbit\appdata\local\programs\python\python37-32\include -Ic:\users\arbit\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/C/sparse.c /Fobuild\temp.win32-3.7\Release\src/C/sparse.obj
    sparse.c
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:/usr/lib /LIBPATH:c:\users\arbit\appdata\local\programs\python\python37-32\libs /LIBPATH:c:\users\arbit\appdata\local\programs\python\python37-32\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86" m.lib lapack.lib blas.lib /EXPORT:PyInit_base build\temp.win32-3.7\Release\src/C/base.obj build\temp.win32-3.7\Release\src/C/dense.obj build\temp.win32-3.7\Release\src/C/sparse.obj /OUT:build\lib.win32-3.7\cvxopt\base.cp37-win32.pyd /IMPLIB:build\temp.win32-3.7\Release\src/C\base.cp37-win32.lib
    LINK : fatal error LNK1181: cannot open input file 'm.lib'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x86\\link.exe' failed with exit status 1181
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\arbit\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\arbit\\AppData\\Local\\Temp\\pip-install-s6rs24i8\\cvxopt\\setup.py'"'"'; __file__='"'"'C:\\Users\\arbit\\AppData\\Local\\Temp\\pip-install-s6rs24i8\\cvxopt\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\arbit\AppData\Local\Temp\pip-record-lzcs604f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\arbit\appdata\local\programs\python\python37-32\Include\cvxopt' Check the logs for full command output.

I looked up a few of the specific errors within the output but it isn't clear to me that any of them are relevant. Anyone have any ideas?

**Comment by rezat96** [comment]
> Running a simple `pip install cvxopt` I get a series of errors:
> 
> > Collecting cvxopt
> > Using cached cvxopt-1.2.5.tar.gz (6.7 MB)
> > Building wheels for collected packages: cvxopt
> > Building wheel for cvxopt (setup.py) ... error
> > ERROR: Command errored out with exit status 1:
> 
> At which point it attempts to install using setup.py, according to this part of the error:
> 
> > DEPRECATION: Could not build wheels for cvxopt which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at [pypa/pip#8368](https://github.com/pypa/pip/issues/8368).
> 
> That attempt then produces this error:
> 
> > ERROR: Command errored out with exit status 1:
> > command: 'c:\users\arbit\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\arbit\AppData\Local\Temp\pip-install-s6rs24i8\cvxopt\setup.py'"'"'; **file**='"'"'C:\Users\arbit\AppData\Local\Temp\pip-install-s6rs24i8\cvxopt\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\arbit\AppData\Local\Temp\pip-record-lzcs604f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\arbit\appdata\local\programs\python\python37-32\Include\cvxopt'
> > cwd: C:\Users\arbit\AppData\Local\Temp\pip-install-s6rs24i8\cvxopt
> >     Complete output (33 lines):
> > running install
> > running build
> > running build_py
> > creating build
> > creating build\lib.win32-3.7
> > creating build\lib.win32-3.7\cvxopt
> > copying src\python\coneprog.py -> build\lib.win32-3.7\cvxopt
> > copying src\python\cvxprog.py -> build\lib.win32-3.7\cvxopt
> > copying src\python\info.py -> build\lib.win32-3.7\cvxopt
> > copying src\python\misc.py -> build\lib.win32-3.7\cvxopt
> > copying src\python\modeling.py -> build\lib.win32-3.7\cvxopt
> > copying src\python\msk.py -> build\lib.win32-3.7\cvxopt
> > copying src\python\printing.py -> build\lib.win32-3.7\cvxopt
> > copying src\python\solvers.py -> build\lib.win32-3.7\cvxopt
> > copying src\python_version.py -> build\lib.win32-3.7\cvxopt
> > copying src\python__init__.py -> build\lib.win32-3.7\cvxopt
> > UPDATING build\lib.win32-3.7\cvxopt/_version.py
> > set build\lib.win32-3.7\cvxopt/_version.py to '1.2.5'
> > running build_ext
> > building 'base' extension
> > creating build\temp.win32-3.7
> > creating build\temp.win32-3.7\Release
> > creating build\temp.win32-3.7\Release\src
> > creating build\temp.win32-3.7\Release\src\C
> > C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\arbit\appdata\local\programs\python\python37-32\include -Ic:\users\arbit\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/C/base.c /Fobuild\temp.win32-3.7\Release\src/C/base.obj
> > base.c
> > C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\arbit\appdata\local\programs\python\python37-32\include -Ic:\users\arbit\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/C/dense.c /Fobuild\temp.win32-3.7\Release\src/C/dense.obj
> > dense.c
> > C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\arbit\appdata\local\programs\python\python37-32\include -Ic:\users\arbit\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /Tcsrc/C/sparse.c /Fobuild\temp.win32-3.7\Release\src/C/sparse.obj
> > sparse.c
> > C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:/usr/lib /LIBPATH:c:\users\arbit\appdata\local\programs\python\python37-32\libs /LIBPATH:c:\users\arbit\appdata\local\programs\python\python37-32\PCbuild\win32 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\ATLMFC\lib\x86" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\lib\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x86" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x86" m.lib lapack.lib blas.lib /EXPORT:PyInit_base build\temp.win32-3.7\Release\src/C/base.obj build\temp.win32-3.7\Release\src/C/dense.obj build\temp.win32-3.7\Release\src/C/sparse.obj /OUT:build\lib.win32-3.7\cvxopt\base.cp37-win32.pyd /IMPLIB:build\temp.win32-3.7\Release\src/C\base.cp37-win32.lib
> > LINK : fatal error LNK1181: cannot open input file 'm.lib'
> > error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x86\link.exe' failed with exit status 1181
> > ----------------------------------------
> > ERROR: Command errored out with exit status 1: 'c:\users\arbit\appdata\local\programs\python\python37-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\arbit\AppData\Local\Temp\pip-install-s6rs24i8\cvxopt\setup.py'"'"'; **file**='"'"'C:\Users\arbit\AppData\Local\Temp\pip-install-s6rs24i8\cvxopt\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(**file**);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, **file**, '"'"'exec'"'"'))' install --record 'C:\Users\arbit\AppData\Local\Temp\pip-record-lzcs604f\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\arbit\appdata\local\programs\python\python37-32\Include\cvxopt' Check the logs for full command output.
> 
> I looked up a few of the specific errors within the output but it isn't clear to me that any of them are relevant. Anyone have any ideas?

same here win10,python3.8.5

**Comment by martinandersen** [comment]
Windows wheels are available for Python 27, 3.5, 3.6, and 3.7 (64 bit only) ([ref](http://cvxopt.org/install/index.html)). As a result, pip tries to compile CVXOPT from source which requires some additional configuration steps (see [Installation instructions](http://cvxopt.org/install/index.html#building-and-installing-from-source)).  

xref #161
