### ISSUE TITLE
Determinstic solution of QP optimization?

### ISSUE THREAD

**Issue by Zhenyu-Li** [cvxopt/cvxopt#178]
Hi, 

I have a problem with the QP solution. The same input of QP problem are given. And normally the  QP solver can find the optimal solution for the problem. However, when I try to solve it again and again (iterative loop, Maybe 500 times...). Sometimes it might raise some non-optimal solution or even Valueerror.  Is the solution of QP problem determinstic or sometimes it might have some deviation? Do you have any idea to make it determinstic?  cvxopt.setseed ? 

Thanks for your help.
B.R.

**Comment by martinandersen** [comment]
How did you install CVXOPT? My guess is that it is a multithreaded BLAS/LAPACK library that is introducing randomness. You may be able to run single-threaded by setting some environment variable (e.g., `export OPENBLAS_NUM_THREADS=1` if you have a CVXOPT binary that is linked against OpenBLAS).

**Comment by martinandersen** [comment]
Closing stale issue. 

@Zhenyu-Li, please comment if you would like it reopened.
