### ISSUE TITLE
The PyPI page has 1.2.5.post1 but here on GitHub there's only 1.2.5

### ISSUE THREAD

**Issue by yurivict** [cvxopt/cvxopt#180]
https://pypi.org/project/cvxopt/#files

For this reason Repology shows that the latest version is 1.2.5.post1, but no other system has it because there is no matching tarball: https://repology.org/project/python:cvxopt/versions

**Comment by martinandersen** [comment]
It is a Windows specific post release (see [PEP 440](https://www.python.org/dev/peps/pep-0440/#post-releases)) that addresses a packaging issue; the source is identical to 1.2.5. This issue should automatically be resolved with the next release of CVXOPT.
