### ISSUE TITLE
[modelling] Full rank requirement in modelling

### ISSUE THREAD

**Issue by Jan-Blaha** [cvxopt/cvxopt#184]
Hi cvxopt, thanks for the great work you're doing!

I wanted to propose a small enhancement into the `solve` function of the `op` class.

It happens from time to time, that I face the following error: `ValueError: Rank(A) < p or Rank([G; A]) < n`, not because of ill-conditioned problem, but because of unnecessary conditions. 
This happens for example in the maxflow in a network LP formulation, when the network is somewhere disconnected.

The solution to this problem is rather trivial because it is enough to remove linearly dependent rows of the matrix A, which can be done in numpy with some numerical tollerance (I'm not fluent with cvxopt matrices, sorry for the conversions :) ) for example using the following snippet:
```
_, r = np.linalg.qr(np.hstack((A, b).T)
indep_rows = np.abs(np.diag(r)) > 1e-9
A = matrix(np.array(A)[indep_rows])
b = matrix(np.array(b)[indep_rows])
```
Unfortunately, to do this, one has to have access to the matrix representation of the problem, which is not accessible when working with the modelling module. Deducing the unnecessary constraints means devoting a lot of time for identifying the conditions where such a thing occurs and further making the modelling code hardly readable & error-prone.

Could something like this be added to the `solve` function as an optional feature (it does add some complexity, of course)? It seems rather simple and without it, one has to copy out and modify the `solve` function themselves, which is quite a bad practise for a production code. Otherwise, the modelling functionality is useless in certain problems, which is IMHO really unfortunate.

Thanks for your time reading this. If you had an idea of how to achieve this in the mantels of your vision of the library, I'm happy to help.

Jan Blaha

**Comment by martinandersen** [comment]
There is some experimental (and undocumented) code that uses regularization to get around the rank requirement. You can try this out by using the options `kktsolver="ldl"` and `kktreg=1e-12` (or some other small number).

**Comment by Jan-Blaha** [comment]
Hi Martin,

I have actually tried this (saw this idea in some other issue). It happened to throw `ValueError: domain error` with the following stacktrace (cvxopt part):
```
File "/home/jan/miniconda3/lib/python3.7/site-packages/cvxopt/modeling.py", line 2629, in solve
    sol = solvers.lp(c[:], G, h, A, b, solver=solver, **kwargs)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/cvxopt/coneprog.py", line 3010, in lp
    dualstart, kktsolver = kktsolver, options = options)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/cvxopt/coneprog.py", line 1395, in conelp
    misc.update_scaling(W, lmbda, ds, dz)
  File "/home/jan/miniconda3/lib/python3.7/site-packages/cvxopt/misc.py", line 450, in update_scaling
    s[:m] = base.sqrt( s[:m] )
```

Now I tried again and realized, that I chose too big  `kktreg` constant. Setting below 1e-7 made the whole thing work perfectly.

Thanks again for your time!
