### ISSUE TITLE
cvxopt/modeling.py", line 1397, in __getitem__     = c[0] index out of range

### ISSUE THREAD

**Issue by OsRas2** [cvxopt/cvxopt#185]
Hi!

I'm using the cvxopt modelling package to try to solve a convex optimiziation problem, defined as

`price_purchase_power.trans() * q`
`problem = op(sum(prod_price) + 1e-6*sum(abs(c)), [q >= 0, q <= supply, -1*c <= -1*capacity_lower_bound, c <= capacity_upper_bound, A_prod * q + A_cap * c == b_demand])`

`problem.solve(format='sparse', solver='glpk', options={'glpk':{'msg_lev':'GLP_MSG_ON'}})`

Where price_purchase_power, supply, capacity_lower_bound, capacity_upper_bound, A_prod. A_cap and b_demand are all constructed with spmatrix

`problem.variables()
[variable(73831,'q'), variable(34744,'c')]`

`problem.constraints()
[<inequality in R^73831>, <inequality in R^73831>, <inequality in R^34744>, <inequality in R^34744>, <equality in R^26058>]`

I've tried running my code both on windows and on Ubuntu and I get the same error message. The problem is based on 6-month hourly data and when running 1-month there is no errors and the code produces expected results. 

`sys.maxsize
9223372036854775807`

I've tried to look up on the maximal dimension supported by cvxopt but all I can find is that it depends on sys.maxsize. 

Is my problem to large for cvxopt?

**Comment by martinandersen** [comment]
What's the error message that you are getting? And are you using the most recent version of CVXOPT?

**Comment by OsRas2** [comment]
> What's the error message that you are getting? And are you using the most recent version of CVXOPT?

I'm using CVXOPT 1.2.5

Here is the full error

Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 499, in <module>
  File "<input>", line 401, in solution
  File "python3.6/site-packages/cvxopt/modeling.py", line 2598, in solve
    t = self._inmatrixform(format)
  File "python3.6/site-packages/cvxopt/modeling.py", line 2477, in _inmatrixform
    for v in variables: vmap[v] = x[vslc[v]]
  File "python3.6/site-packages/cvxopt/modeling.py", line 240, in __getitem__
    return (+self).__getitem__(key)
  File "python3.6/site-packages/cvxopt/modeling.py", line 931, in __getitem__
    f._linear = self._linear[l]
  File "python3.6/site-packages/cvxopt/modeling.py", line 1397, in __getitem__
    = c[0]
IndexError: index out of range

**Comment by martinandersen** [comment]
Thanks. I think this issue will require some debugging. Would you be able to share a self-contained example where this happens?

**Comment by OsRas2** [comment]
Hi!

I managed to create an example based on my problem which produces the same error. If you set "numb_of_hours" to e.g. 1 there will be no error. But with "numb_of_hours" to e.g. 4343 then the error occours.



`import numpy as np`
`import pandas as pd`
`from cvxopt import spmatrix`
`from cvxopt.modeling import variable,   op, sum`
 
`numb_of_hours = 4343`
 
`list_capacity_matrices = numb_of_hours *   [np.array([[0., 3300., 0., 0., 0., 1.],`
`                                    [3300.,   0., 6600., 0., 0., 1.],`
`                                    [0.,   7300., 0., 5100., 0., 1.],`
`                                    [0., 0.,   2000., 0., 615., 1.],`
`                                    [0., 0.,   0., 309., 0., 0.],`
`                                    [100000.,   100000., 100000., 100000., 0., 0.]])]`
 
 
`numb_of_areas = 6`
`numb_capacity = 8 * numb_of_hours`
`numb_prod = 17 * numb_of_hours`
`numb_variables = numb_capacity +   numb_prod`
 
`price_purchase_power = np.array([0.02,   15., 0.001, 0.02, 15., 0.001,`
`                                 0.02, 15.,   50., 10., 0.001, 0.02,`
`                                 15., 50.,   0.001, 79.76, 3000.])`
 
`price_purchase_power =   np.tile(price_purchase_power, (numb_of_hours, 1))`
`price_purchase_power =   price_purchase_power.flatten()*1.0`
`supply = np.array([696, 30, 4300, 2110,   199, 6600, 1619, 759,`
`                   300, 6939, 2000, 680, 167,   300, 300, 944,`
`                   100001])`
`supply = np.tile(supply, (numb_of_hours,   1))`
`supply = supply.flatten()*1.0`
`demand = np.array([1166, 1768, 9380,   2651, 625, 1])`
`demand = np.tile(demand, (numb_of_hours,   1))`
`demand = demand.flatten()*1.0`
`numb_prod_per_area = 17`
`numb_prod_per_area = [3, 3, 5, 4, 1, 1]`
 
`# Solution when supply = demand, with   respect to what is sent.`
`def equality_matrix(numb_of_areas,   numb_prod, numb_prod_per_area):`
`      A_prod_elements = []`
`      A_prod_rows = []`
`      A_prod_cols = []`
`      A_cap_elements = []`
`      A_cap_rows = []`
`      A_cap_cols = []`
`      numb_prod_index = 0`
`      numb_areas_index = 0`
 
`      for k in range(0, numb_of_hours):`
`          index_column_prod = 0`
`          for row in range(0, numb_of_areas):`
`            for nbr_prod in range(0,   numb_prod_per_area[row]):`
`                A_prod_elements.append(1)`
`                A_prod_rows.append(row +   numb_areas_index)`
`                A_prod_cols.append(nbr_prod +   index_column_prod + numb_prod_index)`
`            index_column_prod = nbr_prod + 1   + index_column_prod`
 
`          m = list_capacity_matrices[k]`
`          columns = [str(i) + str(j) for i in range(1, numb_of_areas + 1) for j   in range(1, numb_of_areas + 1)]`
`          df = pd.DataFrame(data=np.zeros([numb_of_areas, len(columns)]),   columns=columns, index=[str(i) for i in range(1, numb_of_areas + 1)])`
 
`          for area in range(0, numb_of_areas):`
`            columns = np.nonzero(m[area,   :])[0]`
`            for col in columns:`
`                if col <= area:`
`                    df.loc[str(area + 1),   str(col + 1) + str(area + 1)] = 1`
`                else:`
`                    df.loc[str(area + 1),   str(area + 1) + str(col + 1)] = -1`
 
`          df = df.loc[:, (df != 0).any(axis=0)]`
`          numb_cables = len(df.columns)`
`          np_cap = df.to_numpy()`
`          temp_rows = np.nonzero(np_cap)[0]`
`          temp_cols = np.nonzero(np_cap)[1]`
`          temp_rows = k*numb_of_areas + temp_rows`
`          temp_cols = k*numb_cables + temp_cols`
 
`          A_cap_rows += temp_rows.tolist()`
`          A_cap_cols += temp_cols.tolist()`
`          A_cap_elements += np_cap[np.nonzero(np_cap)].tolist()`
 
`          numb_prod_index = int(numb_prod_index + numb_prod/numb_of_hours)`
`          numb_areas_index += numb_of_areas`
 
`      A_prod = spmatrix(A_prod_elements, A_prod_rows, A_prod_cols, tc='d')`
`      A_cap = spmatrix(A_cap_elements, A_cap_rows, A_cap_cols, tc='d')`
 
`      return A_prod, A_cap`
 
`def capacity_bounds():`
`      '''Upper and lower bound for what can be sent'''`
 
 
`      capacity_upper_bound = np.zeros((int(sum([len(x[np.nonzero(x)]) for x   in list_capacity_matrices])/2), 1))`
`      capacity_lower_bound = np.zeros((int(sum([len(x[np.nonzero(x)]) for x   in list_capacity_matrices])/2), 1))`
`      index = 0`
`      list_numb_of_capacity_variables = []`
`      for capacity_matrix in list_capacity_matrices:`
`          capacity_matrix_upper = np.triu(capacity_matrix)`
`          temp = np.array([[column for column in   capacity_matrix_upper[capacity_matrix_upper != 0]]]).T`
`          capacity_upper_bound[index: index + len(temp)] = temp`
 
`          capacity_matrix_lower = np.tril(capacity_matrix)`
`          temp = np.array([[column for column in   capacity_matrix_lower[capacity_matrix_lower != 0]]]).T`
`          capacity_lower_bound[index: index + len(temp)] = temp`
`          index += len(temp)`
`          list_numb_of_capacity_variables.append(len(temp))`
 
`      return capacity_upper_bound, capacity_lower_bound,   list_numb_of_capacity_variables`
 
`def solution(demand,   price_purchase_power, supply):`
`      capacity_upper_bound, capacity_lower_bound,   list_numb_of_capacity_variables = capacity_bounds()`
`      A_prod, A_cap = equality_matrix(numb_of_areas, numb_prod,   numb_prod_per_area)`
 
`      b_demand = demand`
`      price_purchase_power = spmatrix((price_purchase_power[:]).tolist(), [i   for i in range(0, len(price_purchase_power))],   len(price_purchase_power)*[0])`
`      b_demand = spmatrix((b_demand[:]).tolist(),   np.nonzero(b_demand)[0].tolist(), len(b_demand)*[0])`
`      supply = spmatrix((supply[:]).tolist(), np.argwhere(supply >= 0)[:,   0].tolist(), len(supply)*[0])`
`      capacity_upper_bound = spmatrix((capacity_upper_bound[:, 0]).tolist(),   np.nonzero(capacity_upper_bound)[0].tolist(),   np.nonzero(capacity_upper_bound)[1].tolist())`
`      capacity_lower_bound = spmatrix((-1*capacity_lower_bound[:,   0]).tolist(), np.nonzero(capacity_lower_bound)[0].tolist(),   np.nonzero(capacity_lower_bound)[1].tolist())`
 
`      '''Variables in the optimization, q for quantity and c for   capacity'''`
`      q = variable(numb_prod, 'q')`
`      c = variable(numb_capacity, 'c')`
`      prod_price = price_purchase_power.trans() * q`
 
`      problem = op(sum(prod_price) + 1e-6*sum(abs(c)), [q >= 0, q <=   supply, -1*c <= -1*capacity_lower_bound, c <= capacity_upper_bound,   A_prod * q + A_cap * c == b_demand])`
 
`      print('Solving will begin')`
`      test = problem.solve(format='sparse', solver='glpk',   options={'glpk':{'msg_lev':'GLP_MSG_OFF'}})`
`      if problem.status == 'primal infeasible':`
`          raise Exception('There exist no solution')`
 
`      return q, c, problem.objective.value(),   list_numb_of_capacity_variables`
 
 
`solution(demand, price_purchase_power,   supply)`

**Comment by martinandersen** [comment]
Thanks for the example. It is a limitation due to the way the sparse matrix is constructed, but there is a quick fix. I'll fix it and post a new release.

**Comment by OsRas2** [comment]
Sounds wonderful! :)

**Comment by martinandersen** [comment]
There's a new version on PyPI. The conda package will be updated shortly.
