### ISSUE TITLE
Incomplete comparison with function strncmp

### ISSUE THREAD

**Issue by Daybreak2019** [cvxopt/cvxopt#193]
### Code snippet
```
static PyObject* solve(PyObject *self, PyObject *args, PyObject *kwrds)
{
      ............
      if (!PyArg_ParseTupleAndKeywords(args, kwrds, "OO|iiii", kwlist,
            &F, &B, &sys, &nrhs, &ldB, &oB)) return NULL;

      #if PY_MAJOR_VERSION >= 3
          if (!PyCapsule_CheckExact(F) || !(descr = PyCapsule_GetName(F)))
                 err_CO("F");
          if (strncmp(descr, "CHOLMOD FACTOR", 14))             -------> The string terminator is not considered.
                 PY_ERR_TYPE("F is not a CHOLMOD factor");
          cholmod_factor *L = (cholmod_factor *) PyCapsule_GetPointer(F, descr);
      #else
          if (!PyCObject_Check(F)) err_CO("F");
          descr = PyCObject_GetDesc(F);
          if (!descr || strncmp(descr, "CHOLMOD FACTOR", 14))    -------> The string terminator is not considered.
                 PY_ERR_TYPE("F is not a CHOLMOD factor");
          cholmod_factor *L = (cholmod_factor *) PyCObject_AsVoidPtr(F);
      #endif
      ............
```

### Description
**Function**: 
solve/spsolve/diag/getfactor
**Call-path**:
       1. solve (Python) -> solve -> strncmp
       2. spsolve (Python) -> spsolve  -> strncmp
       3. diag(Python) -> diag  -> strncmp
       4. getfactor(Python) -> getfactor-> strncmp
**WarningType**: Incomplete comparison.
Out analysis tool reported four warnings about the incomplete comparison of strings as shown above.
When the comparison length is 14, the terminator would be ignored. Hence even the strncmp returns 0, the reality may not match expectations specifically when variable descr depends on external inputs (Python).
For example, descr = "CHOLMOD FACTORMalicious", the comparison still return 0.
Also seen in [solve](https://github.com/Daybreak2019/IssueReport/blob/master/Cvxopt/case-003.png), [spsolve](https://github.com/Daybreak2019/IssueReport/blob/master/Cvxopt/case-003-1.png), [diag](https://github.com/Daybreak2019/IssueReport/blob/master/Cvxopt/case-003-2.png) and [getfactor](https://github.com/Daybreak2019/IssueReport/blob/master/Cvxopt/case-003-3.png)

**Comment by Daybreak2019** [comment]
Anyone can help confirm this issue? thanks.

**Comment by kalvdans** [comment]
Yes, it looks like a bug to me too. We should indeed change to `strcmp` or include the trailing NUL byte in the comparison.

**Comment by sanurielf** [comment]
I thinks best solution will be to implement strcmp(str1, str2) != 0 . I will do a PR on CVXOPT  and also on my own fork ([KVXOPT](https://github.com/sanurielf/kvxopt)) with that change.

**Comment by sanurielf** [comment]
I just checked this part of the code could be updated to use TypeCheck_Capsule. Having that, no string comparison is needed. You can check that umfpack.c has this logic already

```
    if (!PyCapsule_CheckExact(F)) err_CO("F");
    if (SP_ID(A) == DOUBLE) {
        TypeCheck_Capsule(F, descrdFn, "F is not the UMFPACK numeric factor "
            "of a 'd' matrix");
    }
    else  {
        TypeCheck_Capsule(F, descrzFn, "F is not the UMFPACK numeric factor "
            "of a 'z' matrix");
    }
```
