### ISSUE TITLE
How to use C++ to directly call the CVXOPT (C++ code) without any python code?

### ISSUE THREAD

**Issue by zhumingpassional** [cvxopt/cvxopt#206]
In my project, python is forbidden, and I have to use C++ to call CVXOPT, how to do it? Could you please provide several examples?
If I have to use CVXOPT in other CPUs such as ARM, how to solve this problem?

I hope CVXOPT can provide other programming language interface, e.g., C++, JAVA.

**Comment by martinandersen** [comment]
Sorry, CVXOPT is written in Python and C. We are not planning to add a C++/Java interface.
