### ISSUE TITLE
Does CVXOPT still support custom types for variables?

### ISSUE THREAD

**Issue by rileyjmurray** [cvxopt/cvxopt#216]
I'm interested in the feature in ``conelp`` described in this portion of its docstring:
https://github.com/cvxopt/cvxopt/blob/f236615e5bd326daeb6cda511c31d86bcc354747/src/python/coneprog.py#L371-L402

Is this still supported in CVXOPT 1.2 or 1.3? I ask because the main ``conelp`` algorithm makes many calls to ``misc.max_step``, and the Python implementation of ``misc.max_step`` makes calls to BLAS which appear to assume a representation of ``x``.
https://github.com/cvxopt/cvxopt/blob/f236615e5bd326daeb6cda511c31d86bcc354747/src/python/misc.py#L1018

It also seems like there are unavoidable BLAS calls in the main ``conelop`` algorithm (although I admit that it's hard to be sure, since the code is quite long and defines many inner functions).

This leads me to believe that maybe this feature is no longer supported. Is there any example code that shows it in action? Even an old version of CVXOPT would be helpful.

Ping @vbharadwaj-bk.

**Comment by rileyjmurray** [comment]
I've done more digging. I wrote a function to find all BLAS and LAPACK calls that seem unavoidable even with a custom KKT solver:
```
def linalgfuncs(filename, lastline_excl):
    blaslines = []
    lapacklines = []
    f = open(filename, 'rt')
    for line in f.readlines():
        if lastline_excl in line:
            break
        if 'blas.' in line:
            start = line.find('blas.')
            line_trunc = line[start:]
            end = line_trunc.find('(')
            blaslines.append(line_trunc[:end])
        if 'lapack.' in line:
            start = line.find('lapack.')
            line_trunc = line[start:]
            end = line_trunc.find('(')
            lapacklines.append(line_trunc[:end])
    f.close()
    blaslines = list(set(blaslines))
    blaslines.sort()
    lapacklines = list(set(lapacklines))
    lapacklines.sort()
    return blaslines, lapacklines
```
I ran that function on [misc.py](https://github.com/cvxopt/cvxopt/blob/master/src/python/misc.py) and [coneprog.py](https://github.com/cvxopt/cvxopt/blob/master/src/python/coneprog.py),
```
misc_blas, misc_lapack = linalgfuncs('misc.py', 'def kkt')  # stop at kkt solver definitions
main_blas, main_lapack = linalgfuncs('coneprog.py', 'def coneqp')  # stop at coneqp
```
The summary is that there are no BLAS or LAPACK functions used in ``conelp`` which are not already used somewhere in misc.py. The LAPACK functions in misc.py *before* the KKT solvers are
```
    lapack.gesvd
    lapack.potrf
    lapack.syevd
    lapack.syevr
```
while the BLAS functions are
```
    blas.axpy
    blas.copy
    blas.dot
    blas.gemm
    blas.gemv
    blas.ger
    blas.nrm2
    blas.scal
    blas.syr2k
    blas.tbmv
    blas.tbsv
    blas.trmm
    blas.trsm
```
So my guess is that if I wanted to use a custom datatype then I'd need to override all of those functions. Does that sound about right?

For context, I'm interested in working with @vbharadwaj-bk to run some subset of the linear algebra functionality in conelp on a GPU. (Maybe all of the linear algebra, but that's unlikely since the kkt systems that arise in practice typically require sparse direct methods.) It would be great if we could adapt conelp to use [cupy](https://docs.cupy.dev/en/stable/reference/cuda.html), for example.

**Comment by martinandersen** [comment]
This is still supported. Note that `max_step` is used with `s` and `z` as arguments, and these belong to a Cartesian product of standard cones. Only `x` and `y` can be represented using custom types.

**Comment by rileyjmurray** [comment]
Ah! That's great news. It might be helpful to have a simple example in the documentation that shows how to use this feature and comments on its limitations. You've answered my immediate question though, so feel free to close this issue if you'd like.

**Comment by martinandersen** [comment]
I agree, the documentation is very limited when it comes to some of the more advanced features. 
We do have an [example](https://cvxopt.org/examples/mlbook/ubsdp.html) that uses this feature, but it is not in the user's guide, and it isn't clear that it uses custom types until you look at the [code](https://cvxopt.org/_downloads/1b61e24e16f3913331066c181fd3eacf/ubsdp.py).
