### ISSUE TITLE
Explanation of result variables

### ISSUE THREAD

**Issue by abhijith95** [cvxopt/cvxopt#218]
Hey, can I get the explanation of the result variables? I get a dictionary with terms like "primal slack", "dual slack", "primal infeasibility", etc. I want to know mathematically what they mean.

Appreciate with the support. Thanks in advance!

**Comment by martinandersen** [comment]
I'm assuming that you are referring to the dictionary returned by `conelp()`. You can find information about the different keys in the [user guide](http://cvxopt.org/userguide/coneprog.html#linear-cone-programs) as well as in the docstring.
