### ISSUE TITLE
SolverError: The solver GLPK-MI is not installed. (MacOS intel)

### ISSUE THREAD

**Issue by chanansh** [cvxopt/cvxopt#219]
I get the error message:
> SolverError: The solver GLPK-MI is not installed.
However, I have installed the cvxopt both with binaries and without as instructed here:
https://github.com/cvxpy/cvxpy/issues/972

In the latter, it says python 3.9 is not supported. However, in the cvopt repo it says up to 3.10 is supported.

`cp.installed_solvers()`

returns
> ['CVXOPT', 'ECOS', 'ECOS_BB', 'GLPK', 'GLPK_MI', 'OSQP', 'SCIPY', 'SCS']

> cvxopt.__version__
'1.3.0'

> cvxpy.__version__
'1.2.0'

My environment: 
> Python 3.9.12
> macOs 12.3.1

**Comment by martinandersen** [comment]
Does `from cvxopt import glpk` succeed?

**Comment by chanansh** [comment]
Solved by following the official installation guide (not `pip install`).

```
brew install gsl fftw suite-sparse glpk
git clone https://github.com/cvxopt/cvxopt.git
cd cvxopt
git checkout `git describe --abbrev=0 --tags`
export CVXOPT_BUILD_FFTW=1    # optional
export CVXOPT_BUILD_GLPK=1    # optional
export CVXOPT_BUILD_GSL=1     # optional
python setup.py install
```

**Comment by martinandersen** [comment]
But it fails with the pip installed v1.3.0?

**Comment by chanansh** [comment]
No

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by martinandersen** [comment]
I’m assuming that this isn’t an issue with CVXOPT after all, otherwise please reopen.
