### ISSUE TITLE
Where are the glpk binary interface and options documented?

### ISSUE THREAD

**Issue by keithbriggs** [cvxopt/cvxopt#221]
I found that it is possible to do this kind of thing to successfully solve 0-1 (i.e. binary or boolean) LP problems:
```
from cvxopt.glpk import ilp
ilp(c,G,h,B=set(range(n)))
```

But I don't know why this works, as ilp is not mentioned in the docs, and is only defined in the msk.py file, which is for MOSEK (which I don't have).  Where is the B option documented?   In general, is it safe to assume that undocumented features are stable?

Also, how do I turn off trace messages for this?    If find that 

`solvers.options['ilp']={'msg_lev': 'GLP_MSG_OFF'}`

as mentioned int the docs, does not turn off all messages.  I still get this:

```
GLPK Integer Optimizer 5.0
36 rows, 36 columns, 1286 non-zeros
36 integer variables, all of which are binary
Preprocessing...
Objective value =  -5.920000000e+02
INTEGER OPTIMAL SOLUTION FOUND BY MIP PREPROCESSOR
```

**Comment by keithbriggs** [comment]
I have rebuilt GLPK and cvxopt from the latest sources, and I still find that it is impossible to turn off the numerous GLPK trace messages.    GLP_MSG_OFF just has no effect.   I have found that many people have reported this problem on stackoverflow and googlegroups etc. over the last 5 years or so, and a proper fix seems not to exist.

**Comment by martinandersen** [comment]
The documentation is unfortunately limited as you point out. There is some info in the glpk and glpk.ilp docstrings.

```
The GLPK control parameters have the default values listed in 
the GLPK documentation (section 2.8.1 for the simplex solver and 
section 2.10.5 for the MILP solver).  The control  parameters can 
be modified by making an entry in the dictionary glpk.options.
For example, glpk.options['msg_lev'] = 'GLP_MSG_OFF' turns off the 
printed output will be turned off during execution of glpk.lp().
Setting glpk.options['it_lim'] = 10 sets the simplex iteration 
limit to 10.  Unrecognized entries in glpk.options are ignored.
```
