### ISSUE TITLE
GLP_MSG_OFF doesn't work for ilp

### ISSUE THREAD

**Issue by keithbriggs** [cvxopt/cvxopt#222]
I found that adding
```C
iocp.msg_lev = GLP_MSG_OFF;
```

at line 908 of src/C/glpk.c does turn off the unwanted messages.   So somewhere in the block of code above line 908, the GLP_MSG_OFF setting is not getting passed through.   There is a block of code handling the options between lines 701 and 722 which is enclosed by `#if 0` and `#endif,` but there is no comment on why this is.

**Comment by martinandersen** [comment]
You need to add the following line before calling `glpk.ilp()`:

```
glpk.options['msg_lev'] = 'GLP_MSG_OFF'
```

Here's an example:

```
from cvxopt import glpk, matrix
c = matrix([-4., -5.])
G = matrix([[2., 1., -1., 0.], [1., 2., 0., -1.]])
h = matrix([3., 3., 0., 0.])
A = matrix([1.0,1.0],(1,2))
b = matrix(1.0)
glpk.options['msg_lev'] = 'GLP_MSG_OFF'
sol1 = glpk.ilp(c, G, h, A, b, set([0]), set())
```
