### ISSUE TITLE
Import not working for apple M1

### ISSUE THREAD

**Issue by pemeriau** [cvxopt/cvxopt#225]
Hello, 

I have installed `cvxopt` via pip on my Mac M1 which worked but then the `import cvxopt` fails raising the issue: 
"ImportError: dlopen(/.../miniforge3/envs/pcvlown/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so, 0x0002): tried: '/.../miniforge3/envs/pcvlown/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))". 

I have also tried the install without the wheel and the install was failing at `python setup.py install`due to 
"src/C/gsl.c:28:10: fatal error: 'gsl/gsl_rng.h' file not found
#include <gsl/gsl_rng.h>"

**Comment by sanurielf** [comment]
You could try installing gsl before installing cvxopt:

`brew install gsl`
`pip install cvxopt`

Or try [KVXOPT](https://github.com/sanurielf/kvxopt) which has wheels for Mac M1.

**Comment by pemeriau** [comment]
I already `brew install gsl` and I need `cvxopt` to use `picos`. I guess the import of picos will fail if I install KVXOPT instead no?

**Comment by pemeriau** [comment]
And `pip install kvxopt`failed due to not finding ùmfpack.h`.

**Comment by sanurielf** [comment]
Mmmm, I see. Lets try to build CVXOPT with the following commands:


`brew install gsl suitesparse`
`export CVXOPT_SUITESPARSE_INC_DIR=$(brew --prefix)/include`
`export CVXOPT_SUITESPARSE_LIB_DIR=$(brew --prefix)/lib`
`pip install cvxopt`

Please let me know if it works or the errors you get.

**Comment by pemeriau** [comment]
Same error, that it: 

`import cvxopt.base
ImportError: dlopen(/Users/pe/Softwares/miniforge3/envs/pcvlown/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so, 0x0002): tried: '/Users/pe/Softwares/miniforge3/envs/pcvlown/lib/python3.10/site-packages/cvxopt/base.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))`

**Comment by pemeriau** [comment]
It worked when I edited my profile and then redoing the installation

`vi ~/.profile

export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export MANPATH=/opt/local/share/man:$MANPATH
export C_INCLUDE_PATH=/opt/local/include
export CPLUS_INCLUDE_PATH=/opt/local/include
export LIBRARY_PATH=/opt/local/lib
alias gcc="gcc -I/opt/local/include -L/opt/local/lib"
alias g++="g++ -I/opt/local/include -L/opt/local/lib"`

**Comment by nker** [comment]
Hello,

I'm experiencing the same issue and unfortunately editing my profile and reinstalling `cvxopt` did not solve the problem for me. This only occurs with Python 3.10 (arm64). Everything works perfectly fine on arm64 Python 3.9 on Apple Silicon computers even without any changes to my profile.

This is the command that I use to install `cvxopt` based on `suite-sparse` installed with brew:
```
CVXOPT_SUITESPARSE_LIB_DIR=/opt/homebrew/Cellar/suite-sparse/5.13.0/lib/ CVXOPT_SUITESPARSE_INC_DIR=/opt/homebrew/Cellar/suite-sparse/5.13.0/include/ pip install cvxopt
```
There are no errors until I try to import `cvxopt` or `picos`.

It seems like there are some issues that relate specifically to Python 3.10 but I was not able to figure them out so far.
