### ISSUE TITLE
Distributing arm64 wheels

### ISSUE THREAD

**Issue by stephane-caron** [cvxopt/cvxopt#234]
Hi CVXOPT maintainers, and thank you for your work :smiley: This issue is just to let you know that there is demand for arm64 wheels for recent Mac computers: https://github.com/qpsolvers/qpsolvers/issues/189

**Comment by MichaelSchneeberger** [comment]
CVXOPT 1.3.0.1 (from pypi.org) with Pyhton 3.11 works well on Windows

**Comment by martinandersen** [comment]
Version 1.3.1 now has arm64 wheels for macOS 13 / Python 3.9, 3.10 and 3.11

**Comment by carlthome** [comment]
Amazing! Is it possible to also easily offer prebuilt linux/arm64 wheels for those of us who run cvxopt in Docker Desktop on MacBooks?

**Comment by victorlin** [comment]
+1 for linux/arm64 wheels. I'm a user who distributes software that depends on CVXOPT via a Docker image, and currently need to build this dependency from source on linux/arm64 in order to distribute to macOS ARM64 users.
