### ISSUE TITLE
Incomplete/suspicious pypi release

### ISSUE THREAD

**Issue by bemgreem** [cvxopt/cvxopt#236]
Hi,

I just ran into an issue where pip installation failed because the latest version of cvxopt on pypi https://pypi.org/project/cvxopt/1.3.0.1/#files only has windows binaries (no source or linux/osx binaries). As of right now at least. I also notice 1.3.0.1 is not a tag in your repo.

I can obviously solve my issue by using an older version, just wanted to flag on the off chance that this is a security breach and someone's published malicious code. Seemed a bit suspicious to have a partial release on pypi that doesn't match a release in the repo

**Comment by martinandersen** [comment]
This is a rebuild of the Windows wheels with the most recent version of OpenBLAS to address an issue. The CVXOPT source has not changed.

**Comment by Zethson** [comment]
Poetry however doesn't seem to know this and this leads to issues

```
  • Updating cvxopt (1.3.0 -> 1.3.0.1): Failed

  RuntimeError

  Unable to find installation candidates for cvxopt (1.3.0.1)

  at ~/miniconda3/envs/ehrapy/lib/python3.10/site-packages/poetry/installation/chooser.py:109 in choose_for
      105│ 
      106│             links.append(link)
      107│ 
      108│         if not links:
    → 109│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      110│ 
      111│         # Get the best link
      112│         chosen = max(links, key=lambda link: self._sort_key(package, link))
      113│ 

```

**Comment by Zethson** [comment]
@martinandersen this makes cvxopt completely break poetry based projects. I'd kindly request that you please release a 1.3.1 version to fix this.

**Comment by robertodr** [comment]
> @martinandersen this makes cvxopt completely break poetry based projects. I'd kindly request that you please release a 1.3.1 version to fix this.

second this. `cvxopt` is a transitive dependency of our project, but this latest release forces us to pin it explicitly in our `pyproject.toml`

**Comment by panteparak** [comment]
> This is a rebuild of the Windows wheels with the most recent version of OpenBLAS to address an issue. The CVXOPT source has not changed.

I believe the newly tagged version `1.3.0.1` also breaks semver standard. Tagging with `1.3.1` would be a better way to address this problem since there was an UPGRADE to OpenBLAS so that is a patch version increment.

**Comment by martinandersen** [comment]
We will create a new release (1.3.1) once we have addressed some issues in the CI pipeline related to setuptools and versioneer. This is unfortunately also what is delaying the release of a linux/py311 wheel.

**Comment by panteparak** [comment]
@martinandersen is it possible to yanked or removed version `1.3.0.1` on pypi too. Since this break poetry, unless of course a specific version pinning is applied other than major/minor version pinning

**Comment by martinandersen** [comment]
@panteparak, 1.3.0.1 is [PEP 440](https://peps.python.org/pep-0440/#final-releases) compliant, so I think the best solution would be to simply create a new 1.3.1 release. Would that pose a problem for poetry?

**Comment by panteparak** [comment]
> @panteparak, 1.3.0.1 is [PEP 440](https://peps.python.org/pep-0440/#final-releases) compliant, so I think the best solution would be to simply create a new 1.3.1 release. Would that pose a problem for poetry?

To my knowledge it should cause any problem, I can run a quick installation test after a new version release and let you know.
