### ISSUE TITLE
Backtracking problem - Is there a reference for the merit function used in cp/cpl?

### ISSUE THREAD

**Issue by lciti** [cvxopt/cvxopt#246]
I would like to ask if there's a reference for the `cp`/`cpl` implementation (the coneprog.pdf file linked in the documentation covers LP and QP only). I am particularly interested in the merit function, its properties and possibly a proof of the fact that the Newton direction (affine or not) is a descent direction for the merit function. I have tried to infer it from the code but I get a bit lost due to the cp problem being re-framed as a cpl with the envelope.
I have developed an algorithm that uses `cp` and works really well in general but for some data after a few iterations it starts to backtrack heavily due to the Armijo-like condition failing repeatedly until the accepted step becomes so small that the duality gap stops improving.
While intuitively I understand that the Newton direction should decrease `gap + resx + resznl`, I fail to understand how it can be expected to decrease `theta1 * gap + theta2 * resx + theta3 * resznl` for arbitrary `theta`. It would seem to me that the only way would be for each of `gap`, `resx` and `resznl` to be guaranteed to decrease. Is this the case? Am I missing something? A reference where I could find this information would be very useful.
Empirically, setting all three thetas to 1 in lines [717](https://github.com/cvxopt/cvxopt/blob/3b718ee560b3b97d6255c55f0ed7f64cb4b72082/src/python/cvxprog.py#L717)--[719](https://github.com/cvxopt/cvxopt/blob/3b718ee560b3b97d6255c55f0ed7f64cb4b72082/src/python/cvxprog.py#L719) makes the backtracking problem disappear with the few datapoints that I have tried (but this could be a coincidence).
Thanks!

**Comment by martinandersen** [comment]
@lciti, `cpl` uses a backtracking line search and/or a non-monotonic line search. You'll find a short description in [cvxprog.py#L1081](https://github.com/cvxopt/cvxopt/blob/3b718ee560b3b97d6255c55f0ed7f64cb4b72082/src/python/cvxprog.py#L1081). I believe that it is based on the non-monotonic *watchdog technique* described in Nocedal & Wright's [Numerical Optimization](https://link.springer.com/book/10.1007/978-0-387-40065-5).
