### ISSUE TITLE
SDP marked as optimal instead of unbounded

### ISSUE THREAD

**Issue by SteveDiamond** [cvxopt/cvxopt#25]
I found an unbounded SDP problem that CVXOPT marked as solved. Here's CVXPY code to generate it. CVXPY uses the kkt_ldl solver with regularization.

```
from cvxpy import *
X = Variable(5, 5)
obj = Maximize(lambda_min(X))
prob = Problem(obj)
prob.solve(solver=CVXOPT)
c, G, h, dims, A, b = prob.get_problem_data(CVXOPT)
```

**Comment by martinandersen** [comment]
We now skip the initial optimality check when regularization is used. (See 61ec780c8c9137e5fd5c1ab5412b2508b42874cd.)

The following code now returns the status `Certificate of dual infeasibility found.` 
```python 
from cvxpy import *
X = Variable(5, 5)
obj = Maximize(lambda_min(X))
prob = Problem(obj)
P = prob.get_problem_data(CVXOPT)

from cvxopt import solvers
solvers.options['kktreg'] = 1e-6
sol = solvers.conelp(P['c'],P['G'],P['h'],P['dims'],P['A'],P['b'],kktsolver='ldl')
```
However, the CVXPY code returns `Solver 'CVXOPT' failed. Try another solver.` I'm not sure why.

**Comment by SteveDiamond** [comment]
Thanks for making this change! CVXPY now by default uses the CVXOPT Cholesky KKT solver with preprocessing to remove redundant rows. The preprocessing does a QR factorization of A and removes rows from G that are multiples of other rows in G. This destroys the sparsity of A, but it's still a major improvement in performance over the LDL KKT solver, which does a dense LDL factorization. 

Ideally the LDL solver would do a sparse factorization. I've tried to implement this a few times but it's always turned out to be a bigger project than I had time for.

There's still an option to use the old regularized LDL solver without preprocessing A and G:
```
prob.solve(solver=CVXOPT, kktsolver="robust")
```
The ``get_problem_data`` function returns the data used in this second, non-default way of calling CVXOPT. This is confusing and something I should change.
