### ISSUE TITLE
Python 3.13 Binaries 

### ISSUE THREAD

**Issue by PoeticExposition** [cvxopt/cvxopt#254]
Hello, as Python 3.13 has been released, does there exist a pre-built package for this latest stable version of Python? 
Incidentally, please upgrade the [docs](https://cvxopt.org/install/index.html#installing-a-pre-built-package) (“ are available for Python 3.8-3.11” is out-dated) after adding the new wheels.

**Comment by martinandersen** [comment]
We are working on pre-built packages for Python 3.13 and will add these to PyPI as soon as possible.

**Comment by PoeticExposition** [comment]
Many thanks!
