### ISSUE TITLE
CVXOPT fails for problems with no constraints

### ISSUE THREAD

**Issue by SteveDiamond** [cvxopt/cvxopt#26]
CVXOPT returns a solution instead of unbounded for problems with no constraints. Here's CVXPY code to generate such a problem. CVXPY uses the kkt_ldl solver with regularization.
```
from cvxpy import *
x = Variable()
obj = Maximize(x)
prob = Problem(obj)
prob.solve(solver=CVXOPT)
c, G, h, dims, A, b = prob.get_problem_data(CVXOPT)
```

**Comment by martinandersen** [comment]
The following code now returns the status `Certificate of dual infeasibility found.`

```python
from cvxpy import *
x = Variable()
obj = Maximize(x)
prob = Problem(obj)
P = prob.get_problem_data(CVXOPT)

from cvxopt import solvers
solvers.options['kktreg'] = 1e-6
sol = solvers.conelp(P['c'],P['G'],P['h'],P['dims'],P['A'],P['b'],kktsolver='ldl')
```

However, `prob.solve(solver=CVXOPT)` fails with the message `Solver 'CVXOPT' failed. Try another solver.`

**Comment by SteveDiamond** [comment]
Thanks! It works for me too.
