### ISSUE TITLE
L1-norm regularized least-squares ||Ax - b||^2 + lambda || C x ||_1

### ISSUE THREAD

**Issue by chrichat** [cvxopt/cvxopt#35]
I would like to ask how is it possible to solve the aforementioned equation with cvxopti

||Ax - b||^2 + lambda || C x ||_1

The L1-norm regularized least-squares function, it solves the equation without the Matrix C , how can i adapt the  script?

Thank you in advance

**Comment by martinandersen** [comment]
The Github issue tracking system is for bugs and feature requests only. Other questions should be posted here: https://groups.google.com/forum/#!forum/cvxopt
