### ISSUE TITLE
Pass solver options as dict instead of having a global variable.

### ISSUE THREAD

**Issue by SteveDiamond** [cvxopt/cvxopt#37]
Could CVXOPT be changed so the solver options are passed as a dict into the various solve methods instead of having a global variable?

I'm running into race conditions involving the global ``cvxopt.solvers.options`` dict when testing CVXPY with nose.

**Comment by martinandersen** [comment]
Thanks for the suggestion! We'll add this in the next release.

**Comment by martinandersen** [comment]
This has now been implemented in the dev-branch. 
(8a65d271863980b7ae83a6d36fae078265ec870f, 7c5aa14fa91e1718079eb6a4295f939ceff212ab, 76f42d050547f72470e064636d08a268024e1e66, 3212cd52055a5ce7938024b592a8215f7d6627f8)
