### ISSUE TITLE
Is cvxopt 1.1.7 compatible with mosek 6?

### ISSUE THREAD

**Issue by necozay** [cvxopt/cvxopt#41]
`INSTALL` document talks about mosek 6; `msk.py` says it is an interface to mosek 7. I have mosek 6 and cvxopt 1.1.7. I am getting the following error:
```
...
  File "build/bdist.linux-x86_64/egg/cvxopt/coneprog.py", line 2890, in lp
  File "build/bdist.linux-x86_64/egg/cvxopt/msk.py", line 162, in lp
AttributeError: Task instance has no attribute 'getsolsta'
```
Just wanted to check if this is a known incompatibility or if I should look for another bug. Thanks.

**Comment by martinandersen** [comment]
This is a typo in the `INSTALL` document. CVXOPT 1.1.7 works with MOSEK 7.
