### ISSUE TITLE
L1 norm approximation - Illegal value of ldB

### ISSUE THREAD

**Issue by MrVampy** [cvxopt/cvxopt#43]
Also posted [here][1].

Following the example on L1 norm approximation given [here][2], with the following code,

    from l1 import l1
    from cvxopt import normal

    m, n = 500, 100
    P, q = normal(m,n), normal(m,1) 
    u = l1(P,q)

everything works okay. 

However when I change *m* to be smaller than *n*,

    from l1 import l1
    from cvxopt import normal

    m, n = 50, 100
    P, q = normal(m,n), normal(m,1) 
    u = l1(P,q)

I get the following error:

    ValueError: illegal value of ldB

I can see that the error is caused by the following statement in L1.py:180:

    lapack.gels(+P, uls)

and diving further down into lapack.c:3651, the following statement throws the error:

    if (ldB < MAX(MAX(1,n),m)) err_ld("ldB");

However, when I read the documentation on [CVXOPT's LAPACK interface for cvxopt.lapack.gels][3], it specifically says, that when *m* is less than *n*, it solves a least norm problem.

Can anyone shed some light on why having *m* smaller than *n* does not work?

  [1]: http://stackoverflow.com/questions/32552068/cvxopt-l1-norm-approximation-illegal-value-of-ldb
  [2]: http://cvxopt.org/examples/mlbook/l1.html
  [3]: http://cvxopt.org/userguide/lapack.html#least-squares-and-least-norm-problems

**Comment by martinandersen** [comment]
Notice that the optimal value is zero when m < n and the equation A\*x = b is consistent. This implies that any solution to the underdetermined system A\*x = b is also a solution to the optimization problem. The l1 example code is intended for the case when m > n.

The error that you get has to do with how lapack.gels() routine works. Here's an excerpt from the docstring:

```
A is an m by n matrix.  B has nrhs columns.  On exit, B is
replaced with the solution, and A is replaced with the details
of its QR or LQ factorization.
```

Notice that when solving a least-norm problem of the form A\*x = b, the vector b is shorter than the solution vector x, so to store the vector x, the lapack.gels() routine requires the second input `B` to be vector or matrix that is large enough to hold the solution x. Here's an example:

```python
m,n = P.size
x = matrix([q,matrix(0.0,(n-m,1))])
lapack.gels(+P,x)
print(blas.nrm2(P*x-q))
```

**Comment by MrVampy** [comment]
Thank you Martin, I appreciate your answer. I was actually trying to solve an L1 norm problem of an underdetermined system, and ended up using the following formulation in CVXPY, given that your example worked for m > n only:

    x = cvx.Variable(n)
    obj = cvx.Minimize(cvx.norm(x,1))
    const = [A * x == b]
    prob = cvx.Problem(obj,const)
    result = prob.solve()

It worked like a charm :-)

**Comment by coderkhaleesi** [comment]
I would add this to get the variable values:

   prob.solve()
   for variable in prob.variables():
           print("Variable %s: value %s" % (variable.name(), variable.value))
