### ISSUE TITLE
Mosek interface prints empty lines with suppressed output

### ISSUE THREAD

**Issue by pettni** [cvxopt/cvxopt#47]
The following minimal example reproduces the bug:

```python
import mosek
from cvxopt import msk, matrix

A = matrix([[1.,0.],[0.,1.]])
b = matrix([1.,1.])
c = matrix([-1.,-1.])

msk.options = {mosek.iparam.log: 0} # supposed to suppress output
msk.lp(c,A,b) # prints four empty lines.
```

This is a bug related to Mosek internals, but can easily be fixed by redefining `streamprinter()` in `msk.py` ([here](https://github.com/cvxopt/cvxopt/blob/master/src/python/msk.py#L30)) as follows:

```python
def streamprinter(text): 
    sys.stdout.write(text) 
    sys.stdout.flush() 
```
This is the stream printer used in [mosek tutorials](http://docs.mosek.com/7.1/pythonapi/Linear_optimization.html).

**Comment by martinandersen** [comment]
Thanks for pointing this out. We'll update this in the next release.

**Comment by martinandersen** [comment]
This has now been updated in the dev branch (https://github.com/cvxopt/cvxopt/commit/344eb6c7307ddf24715e8de9662217a9e29e8cf6, https://github.com/cvxopt/cvxopt/commit/36f7e63e36436d6a915dece4083b40263d3d3248).
