### ISSUE TITLE
Dimensionality issue with lower and upper inequality constraints in solvers.qp().

### ISSUE THREAD

**Issue by fazzolini** [cvxopt/cvxopt#49]
I am trying to solve a quadratic problem with both lower and higher bound inequality constraints.
My code worked perfectly when I just had lower bound inequality constraint, so my matrix G was a 3 by 3 matrix, and vector h was 3 by 1 . Then I decided to add upper bound inequality constraint, so my matrix G now needs to be 6 by 3, and vector h 6 by 1. However, upon optimizing, the result is now 6 x 1 vector, and not 3 x 1, which I cannot understand.

According to tutorial at MIT over here:

https://courses.csail.mit.edu/6.867/wiki/images/a/a7/Qp-cvxopt.pdf

it says it is possible to have both upper and lower bound constraints and follows through, in their case they have G matrix 5 x 2 and vector h 5 x 1, and the output they get has dimensionality of 2 x 1.

In my case I have:
dim(G) = (6,3)
dim(h) = (6,1)
And dim(solution_from_cvxopt) = (6,1)

Whereas it is expected to be dim(w) = (3,1)

So the question is: is this a bug or two sets of inequality constraints are not allowed?

Here is the sample code that outputs a 6 by one vector.
```
n = 3
P = cvxopt.matrix(var_covar2.values) # var_covar is pandas DataFrame with dimensions 3 x 3
q = cvxopt.matrix(0.0, (n, 1))

G = cvxopt.matrix(np.array([[-1, 0, 0], [0, -1, 0], [0, 0, -1],[1, 0, 0],[0, 1, 0], [0, 0, 1]]), tc = 'd')
h = cvxopt.matrix(np.array([0, 0, 0, 1, 1, 1]), tc = 'd')

upper_matrix_A = returns2.mean() # returns2 is pandas DataFrame with dimensions 1 x 3
lower_matrix_A = np.ones(n)  # numpy array with dimensions 1 x 3
matrix_A = np.vstack([upper_matrix_A, lower_matrix_A]) # creates 2 x 3 numpy array
A = cvxopt.matrix(matrix_A) # converts 2 x 3 array into cvxopt matrix
b = cvxopt.matrix([0.5, 1.0], (2,1)) # vertical matrix with dimenstions 2 x 1

solver = cvxopt.solvers.qp(P, q, G, h, A, b)
print solver['s']
```

In the images I provide excerpt from the MIT tutorial:
<img width="914" alt="screen shot 2016-01-27 at 19 26 53" src="https://cloud.githubusercontent.com/assets/12122269/12622089/6ae77c12-c52c-11e5-9c1a-97b6a26ae006.png">

In their case matrix G is 5 x 2 and h is 5 x 1, their solution from cvxopt is 2 x 1.

<img width="477" alt="screen shot 2016-01-27 at 19 30 05" src="https://cloud.githubusercontent.com/assets/12122269/12622096/753c31a8-c52c-11e5-94b9-474e3f513b7f.png">

**Comment by martinandersen** [comment]
The inequality G*x <= h is represented as G*x + s == h where the vector s is a nonnegative slack variable. The length of s is therefore equal to the number of rows in G. The dictionary returned by the solver also contains a vector x, the length of which is equal to the number of columns in G.

**Comment by fazzolini** [comment]
@martinandersen thank you very much for such quick answer! I got lost in documentation and didn't know about other keys such as x in the resulting dictionary.
