### ISSUE TITLE
Domain Error in cvxopt/misc.py

### ISSUE THREAD

**Issue by fazzolini** [cvxopt/cvxopt#50]
I am running an optimizer and get the following error message:
```python
PortfolioOptimizer.py in markowitz_cvxopt_optimizer(self, exp_ret, var_covar, risk_level, asset_weight_bound, verbose)
    127                 cvxopt.solvers.options['show_progress'] = verbose
    128                 # solve the problem
--> 129                 portfolio_solver = cvxopt.solvers.qp(P, q, G, h, A, b)
    130 
    131                 # solution

/python2.7/site-packages/cvxopt/coneprog.pyc in qp(P, q, G, h, A, b, solver, initvals, **kwargs)
   4466             'residual as dual infeasibility certificate': dinfres} 
   4467 
-> 4468     return coneqp(P, q, G, h, None, A,  b, initvals, options = options)

/python2.7/site-packages/cvxopt/coneprog.pyc in coneqp(P, q, G, h, dims, A, b, initvals, kktsolver, xnewcopy, xdot, xaxpy, xscal, ynewcopy, ydot, yaxpy, yscal, **kwargs)
   2515 
   2516         # Update lambda and scaling.
-> 2517         misc.update_scaling(W, lmbda, ds, dz)
   2518 
   2519 

/python2.7/site-packages/cvxopt/misc.py in update_scaling(W, lmbda, s, z)
    448     m = mnl + ml
    449     # print "sum of s[:m] =", sum(s[:m])
--> 450     s[:m] = base.sqrt( s[:m] )
    451     z[:m] = base.sqrt( z[:m] )
    452 

ValueError: domain error
```

Then I tried to print `sum(s[:m])` on line 450 to see what is happening and this is what I am getting:
```python
sum of s[:m] = 39.2405768931
sum of s[:m] = 67.0473911353
sum of s[:m] = 53.9637597279
...
...
sum of s[:m] = 3.90475799241e+126
sum of s[:m] = 3.90475799242e+126
sum of s[:m] = 1.64422285248e+127
sum of s[:m] = nan
```
Is there a way to terminate optimization with `Terminated (singular KKT matrix).` message as it usually happens if the matrix is singular? Like this:

```python
sum of s[:m] = 40.207637727
sum of s[:m] = 67.9319998056
sum of s[:m] = 54.8445492522
sum of s[:m] = 41.8585433724
sum of s[:m] = 41.2207850847
sum of s[:m] = 49.296380278
sum of s[:m] = 64.5095349528
sum of s[:m] = 87.099407872
sum of s[:m] = 114.633116206
sum of s[:m] = 103.287626749
sum of s[:m] = 74.9000938688
sum of s[:m] = 64.6947849353
sum of s[:m] = 160.568261528
Terminated (singular KKT matrix).
```

**Comment by martinandersen** [comment]
There are a couple of things that you can try:

1) Check how your constraints are scaled and rescale if necessary (see e.g. https://groups.google.com/forum/#!topic/cvxopt/IstFuvQqXtM or https://groups.google.com/forum/#!topic/cvxopt/MeEq5Q1Har0).

2) Change the default tolerances in the options dictionary (see http://cvxopt.org/userguide/coneprog.html#algorithm-parameters).

If these suggestions do not help, I'd be happy to help if you can send me a problem instance.

**Comment by fazzolini** [comment]
Thanks, your suggestions really helped! It turns out I did not really need an exact solution, so I just wrote a try-except loop and whenever the optimizer crashed with the above mentioned domain error the algorithm just relaxed some constraints, and the problem eventually had a solution.

**Comment by ShubhankarKapoor** [comment]
Hi,
I have tried many different ways for optimising it, changing the abstol, reltol but it still somehow shows me the exact same error.

These are the sizes of my parameters:
P = matrix(H1) # matrix 96*96
q = matrix(np.zeros(96)) # 0's column vector
G = matrix(A1bar) # 192 * 96
h = matrix(b1) # 192 * 1
A = matrix(A2) # 49 * 96
b = matrix(b2) # 49 * 1

Not sure what should I try.
Any help will be appreciated.

Cheers

**Comment by dachun2** [comment]
May I ask why changing default tolerance can solve this problem?

**Comment by martinandersen** [comment]
@dachun2, the default tolerances may be too strict if the problem is poorly conditioned.
