### ISSUE TITLE
Rank of G in QP for Support Vector Regression

### ISSUE THREAD

**Issue by nsarafianos** [cvxopt/cvxopt#54]
The SVR problem [1] has as constraints: 0<= α <= C and 0<= α* <= C. Since x will be represented as [α ; α*] the G matrix will be [ -1 0 ; 0 -1 ; 1 0 ; 0 1] where ; represents a line change. In that case, h = [ 0 ; 0 ; C ; C]
As you can see G has rank 2 and thus, I'm receiving an error while using the cvxopt qp solver. Tried the same in Matlab with the quadprog. When I used lower bounds and upper bounds (without any inequality constraints) it worked, whereas when I removed the lb and ub and added these as inequality constraints I received the same error. 

Do you have any suggestions on how to overcome this? 

Thank you

[1] [http://www.svms.org/regression/SmSc98.pdf](http://www.svms.org/regression/SmSc98.pdf) page 6 of the pdf Eq. 9

**Comment by martinandersen** [comment]
Could you provide a small example? To me it looks like the matrix G should have rank n if x is an n-vector, i.e., using MATLAB notation, G = [ -eye(n); eye(n)].

**Comment by nsarafianos** [comment]
Martin thank you for your reply, it worked now. For future reference for everyone, since x is represented as [α; α*] which has size 2nx1 (n the size of α and α*). Thus, G will be as you said and will have size 4nx2n and now it can be multiplied properly with x. 

Thanks again for your feedback
