### ISSUE TITLE
Don't know how to turn SDP into vectorized form

### ISSUE THREAD

**Issue by wangdingkang** [cvxopt/cvxopt#56]
I am just started to learn SDP, and trying to use cvxopt on Python.
The sdp problem is like:
minimize 1,
s.t.
Dot(Ai, X) >= di-
Dot(Ai, X) <= di+
X is symmetric, and positive semidefinite.

The entries in X are variables.
There is nothing need to be minimized, we just need to find a feasible solution.
Ai are give matrices, di-, di+ are known real values, Dot(A, B) means the dot product of two matrices, that is Dot(A, B) = sum(aij * bij).

**Comment by discardthree** [comment]
You might find the example in the Semidefinite Programming section of the user guide helpful.  http://cvxopt.org/userguide/coneprog.html#semidefinite-programming

Also, you might like cvxpy, which basically adds an interface layer so you can model your problems in a more intuitive way.  It's a separate package from cvxopt but they go together great. :)  http://www.cvxpy.org
