### ISSUE TITLE
Real Time library not linked against on Linux

### ISSUE THREAD

**Issue by jakirkham** [cvxopt/cvxopt#58]
SuiteSparse likes to use the Real Time library on Linux. If cvxopt is built without linking to the Real Time library (as occurs in the 1.1.8 release), some of the examples will fail. Adding this flag ( `-lrt` ) on Linux will solve that problem. Note that this flag cannot be used on Mac as this library does not exist there nor is it used by SuiteSparse.

**Comment by martinandersen** [comment]
Thanks for pointing this out—we'll address this in the next release. Which of the examples fail without the -lrt flag? 

Note that we are including the SuiteSparse source to ease installation, but it is also possible to link against an existing SuiteSparse library by setting the environment variable CVXOPT_SUITESPARSE_EXT_LIB. This may be a better approach on systems where SuiteSparse is available through a package manager.

**Comment by jakirkham** [comment]
So, we are using the examples as a makeshift test suite as I couldn't tell how to run a standard test suite in `cvxopt`. Maybe you have some better ideas of how to test it. As a result, I can't tell you all of the places this would occur, but I can tell you the first place I ran into the problem.

It was in this example `cvxopt-1.1.8/examples/doc/chap7/covsel.py`. The traceback is below. Also, here's the [log]( https://circleci.com/gh/conda-forge/staged-recipes/3978 ) if you need it.

```
Traceback (most recent call last):
  File "covsel.py", line 4, in <module>
    from cvxopt import matrix, spmatrix, log, mul, blas, lapack, amd, cholmod
ImportError: /opt/conda/envs/_test/lib/python2.7/site-packages/cvxopt/amd.so: undefined symbol: clock_gettime
```

**Comment by martinandersen** [comment]
We may have already addressed this issue in the dev branch a while back by adding the NTIMER macro when compiling the AMD package (9d55fa22ec849d460444fa08d17a841f5b3e06c1).

**Comment by jakirkham** [comment]
> Note that we are including the SuiteSparse source to ease installation, but it is also possible to link against an existing SuiteSparse library by setting the environment variable CVXOPT_SUITESPARSE_EXT_LIB. This may be a better approach on systems where SuiteSparse is available through a package manager.

This is the long term strategy for us I think. However, SuiteSparse is not already packaged. I have written down in an issue ( https://github.com/conda-forge/cvxopt-feedstock/issues/1 ) and am working on a proposal that would add SuiteSparse ( https://github.com/conda-forge/staged-recipes/pull/655 ). I decided not to hold up packaging of cvxopt over this issue. Once we have a SuiteSparse package, we will go over to our own package.

Sort of tangential, but I believe cvxopt comes with SuiteSparse 4.4.5 have you or do you know of others who have tried using 4.5.3 or anything in 4.5.x. It looks like it comes with METIS and builds shared libraries.

This last point I think gets us back on topic as my concern is that we need this flag because SuiteSparse builds static libraries. I expect that Tim, et al. are wisely choosing not to include these symbols in the static libraries. The net result is not picking them up from another library as it cannot link, but instead having missing symbols. There is probably similar behavior with GOMP. If it builds dynamic libraries and cvxopt uses those instead, it will at least be linked against `rt` and have some notion of where it lives.

**Comment by jakirkham** [comment]
> We may have already addressed this issue in the dev branch a while back by adding the NTIMER macro when compiling the AMD package (9d55fa2).

So, maybe it is just time for a new release. 😉

**Comment by martinandersen** [comment]
I personally haven't tried installing CVXOPT with SuiteSparse 4.5.x. As far as I recall from the SuiteSparse documentation, the NTIMER macro is used when the timing routines aren't needed, so I don't think that there should be any issues with newer versions of SuiteSparse as long as the NTIMER macro is enabled.

And yes, it is indeed time for a new release, but unfortunately it will probably have to wait until the spring semester is over.

**Comment by jakirkham** [comment]
> As far as I recall from the SuiteSparse documentation, the NTIMER macro is used when the timing routines aren't needed, so I don't think that there should be any issues with newer versions of SuiteSparse as long as the NTIMER macro is enabled.

I see. So, is this just being used for benchmarking then?

> And yes, it is indeed time for a new release, but unfortunately it will probably have to wait until the spring semester is over.

No worries. Just a friendly nudge. 😄

**Comment by martinandersen** [comment]
Version 4.5.3 of SuiteSparse appears to be a bit different, so this is something that we'll have to look into. Looking at SuiteSparse_config.mk in version 4.5.3, it appears that the -lrt flag will automatically be added on Linux systems:
```
    ifeq ($(UNAME),Linux)
        # add the realtime library, librt, and SuiteSparse/lib
        LDLIBS += -lrt -Wl,-rpath=$(INSTALL_LIB)
    endif
```

**Comment by jakirkham** [comment]
So, I think this commit ( https://github.com/cvxopt/cvxopt/commit/007c1a0ea9df9a54e9f99cacbde56a6047518375 ) that we cooked up should make it easier to fix this issue. We just need to use `RT_LIB` in the non-extension case as well.

**Comment by martinandersen** [comment]
Is this necessary with the addition of the NTIMER macro in the AMD extension in setup.py?
