### ISSUE TITLE
glpk output shown, no effect of silencing

### ISSUE THREAD

**Issue by johnyf** [cvxopt/cvxopt#63]
On Debian testing (stretch) with `glpk == 4.60` and `cvxopt @` cc57a9518edcfe129621d179242587f0bd52cbe5 (branch `dev`) none of the following:

```python
solvers.options['show_progress'] = False
solvers.options['LPX_K_MSGLEV'] = 0
solvers.options['msg_lev'] = 'GLP_MSG_OFF'
```

in the module [`polytope.polytope`](https://github.com/tulip-control/polytope/blob/74f1a8c71c496ecb3c5cc1a5e841663acc7e559a/polytope/polytope.py#L71) succeeds in silencing `glpk`. The solver is called with:

```python
sol = solvers.lp(
    matrix(c), matrix(G), matrix(h),
    None, None, 'glpk')
```

over [here](https://github.com/tulip-control/polytope/blob/74f1a8c71c496ecb3c5cc1a5e841663acc7e559a/polytope/polytope.py#L2177).
The output produced looks like this:

```
GLPK Simplex Optimizer, v4.60
8 rows, 3 columns, 16 non-zeros
*     0: obj =   0.000000000e+00 inf =   0.000e+00 (1)
*     3: obj =  -5.000000000e-01 inf =   0.000e+00 (0)
OPTIMAL LP SOLUTION FOUND
GLPK Simplex Optimizer, v4.60
4 rows, 3 columns, 8 non-zeros
*     0: obj =   0.000000000e+00 inf =   0.000e+00 (1)
*     3: obj =  -1.000000000e+00 inf =   0.000e+00 (0)
...
```

Please let us know whether there is something wrong with the verbosity configuration, or this is a `cvxopt` bug.

**Comment by johnyf** [comment]
This behavior arises with `cvxopt == 1.1.8`, but not with `cvxopt == 1.1.7`.

**Comment by martinandersen** [comment]
We changed the way options are passed to GLPK, MOSEK, etc. in 1.1.8. 

"The control parameters listed in the GLPK documentation are set to their default values and can be customized by making an entry in solvers.options['glpk']. The entry must be a dictionary in which the key/value pairs are GLPK parameter names and values."

**Comment by johnyf** [comment]
Thank you, the configuration was updated to be compatible with `cvxopt >= 1.1.8`.

**Comment by tomkimpson** [comment]
To clarify: how would one make an entry in solvers.options['gulp'], so as to silence the output?

**Comment by johnyf** [comment]
Like this: https://github.com/tulip-control/polytope/commit/4650577b3de2104f5483197ff53e90c0188fa3ac

**Comment by tomkimpson** [comment]
Perfect, thanks!
