### ISSUE TITLE
Any call of lapack.gels gives ValueError: -10

### ISSUE THREAD

**Issue by ilkerhk** [cvxopt/cvxopt#64]
Hi, 
I've tried several examples they all give 
   ValueError: -10
error at the line 
   lapack.gels

For example this one : 
 http://cvxopt.org/examples/mlbook/l1.html

I am using freshly installed anaconda and cvxopt package.
Thanks.

**Comment by martinandersen** [comment]
This is most likely a problem with the anaconda distribution. Which version of anaconda and what OS are you using?

**Comment by martinandersen** [comment]
I'm not sure. Since it is a problem with a LAPACK routine, I am guessing that it may have something to do with anaconda switching to MKL. Perhaps you could try following the steps described under "Uninstalling MKL" on the following page: https://docs.continuum.io/mkl-optimizations/index

**Comment by ilkerhk** [comment]
I am really new to python and cvxopt. I am currently a user of  Matlab+cvx and now investigating an alternative python+cvxopt (for a possible migration)...
I will try your suggestion after researching/understanding what are MKL, LAPACK etc...
thanks.

**Comment by ilkerhk** [comment]
When I run the same script mentioned in OP using "python test.py"  I am getting the error : 
Intel MKL FATAL ERROR: Cannot load libmkl_mc3.so or libmkl_def.so.

when I run in spyder I get "ValueError: -10". 

The first error seems common and its solution seems same as what you suggested : 
https://github.com/scikit-learn/scikit-learn/issues/5046

Why I am getting different error messages for the same script with the same interpreter is a mystery for me...

Anyways, I followed the suggestion and it solved my issue, both methods now run error free. Thanks.

**Comment by ilkerhk** [comment]
I've just realized switching to earlier cvxopt built also solves the issue without needing to remove MKL.

conda install cvxopt=1.1.8=py35_0

**Comment by martinandersen** [comment]
Great, thanks for the update.

**Comment by rickantonais** [comment]
I'm having the same trouble but on python 3.6 and windows 10.
There isn't any cvxopt package on version 1.1.8 any longer, the oldest version I can find is 1.1.9 for python 2.7
I'm having a `value error : -7`

**Comment by martinandersen** [comment]
@rickantonais, have you tried installing CVXOPT from the conda-forge channel?
