### ISSUE TITLE
Unsuppressed output even with 'show_progress'=False

### ISSUE THREAD

**Issue by aspiringinsomniac** [cvxopt/cvxopt#65]
@martinandersen 

I think the following two lines should have a preceding `if show_progress:` as it appears in many other places in the code.

https://github.com/cvxopt/cvxopt/blame/8e16f3b44bc0c3fc3490d53336eb92c23735dd46/src/python/coneprog.py#L2268

https://github.com/cvxopt/cvxopt/blame/8e16f3b44bc0c3fc3490d53336eb92c23735dd46/src/python/coneprog.py#L2412

**Comment by martinandersen** [comment]
Thanks for pointing this out. We fixed this some time ago in the dev branch (9d55fa22ec849d460444fa08d17a841f5b3e06c1), so it will be included in the next release.
