### ISSUE TITLE
64-bit Windows installation: conda install creates .egg

### ISSUE THREAD

**Issue by pgkirsch** [cvxopt/cvxopt#66]
I apologize in advance if this is out of scope and/or not cvxopt specific.

I am installing cvxopt on 64-bit Windows 7 using `conda install -c omnia cvxopt`. This added `cvxopt.pth` and `cvopt-1.1.8-py2.7-win-amd64.egg` to my `site-packages` instead of `cvxopt/` and `cvopt-1.1.8-py2.7-win-amd64.egg-info` as I would have expected. Although the installation seemed to work - to the extent that I could import and use cvxopt - the `.egg` seemed to make things unusually slow (python spent a lot of time calling zipimporter). I was able to resolve this by running `unzip cvxopt-1.1.8-py2.7-win-amd64.egg` in my `site-packages` directory (and also `mv EGG-INFO/ cvxopt-1.1.8-py2.7-win-amd64.egg-info/`). Is there a deliberate reason that the `conda install` creates a `.egg` file? And is there a more elegant way of overcoming it than the method I used?

**Comment by martinandersen** [comment]
Unfortunately I don't know the answer, but perhaps the conda people can help: https://github.com/conda-forge/cvxopt-feedstock

**Comment by pgkirsch** [comment]
OK, thanks anyway!
