### ISSUE TITLE
Segfault for large QP problem sizes

### ISSUE THREAD

**Issue by jstraub** [cvxopt/cvxopt#68]
I am trying to solve a large QP but I am getting a segfault beyond some number of constraints. For smaller problems it works just fine (343256 constraints and a P matrix of dimension 16384 by 16384).

**Comment by martinandersen** [comment]
Can you try if the problem occurs with the dev branch on Github? If the problem persists, perhaps you can provide an minimal example?

**Comment by jstraub** [comment]
I am sorry I dont have access to the data anymore. I ended up using the SCS solver directly which worked (https://github.com/cvxgrp/scs)
