### ISSUE TITLE
How to set time limit or iterations limit?

### ISSUE THREAD

**Issue by smehida** [cvxopt/cvxopt#69]
HI,
How to set time limit or iterations limit?

> status,solution = glpk.ilp(W, G.T, h,B=set(range(len(W))))

**Comment by martinandersen** [comment]
The control parameters listed in the GLPK documentation are set to their default values and can be customized via glpk.options. This must be a dictionary in which the key/value pairs are GLPK parameter names and values. For example, the command

```
>>> from cvxopt import glpk
>>> glpk.options = {'msg_lev' : 'GLP_MSG_OFF'}
```
turns off the screen output.
