### ISSUE TITLE
Unclear how to specify linear inequality constraints when calling cvxopt.msk.ilp(...)

### ISSUE THREAD

**Issue by mikeroberts3000** [cvxopt/cvxopt#70]
Hello there,

If possible, I would like to use the MOSEK interface in CVXOPT to solve an ILP problem with linear inequality constraints. However, when I examine the docs and source code for the cvxopt.msk.ilp(...) function, it is not clear how to specify the linear inequalities. It seems surprising to me that linear inequalities aren't supported in MOSEK's mixed integer solver. But they might not be supported in CVXOPT.

Are linear inequalities supported in the CVXOPT interface to MOSEK? Is there some way to pass in the relevant matrix and vectors that I'm not seeing?

Here is the relevant doc string.

```
Signature: cvxopt.msk.ilp(c, G, h, A=None, b=None, I=None)
Docstring:
Solves the mixed integer LP

    minimize    c'*x       
    subject to  G*x + s = h
                A*x = b    
                s >= 0
                xi integer, forall i in I
                
using MOSEK 7.0.

...
```

Thanks so much for your help  :)

**Comment by martinandersen** [comment]
You can think of `G*x + s = h, s >= 0` as linear inequalities, since eliminating `s` yields `G*x <=  h`.

**Comment by mikeroberts3000** [comment]
Ah, of course. This was a silly question. Thanks again so much for your help :)
