### ISSUE TITLE
[modeling, optimization] sparse dictionary representation in objective

### ISSUE THREAD

**Issue by choltz95** [cvxopt/cvxopt#73]
Hi the issue is with applying a dictionary transformation D to my objective function x. 
The convex problem formulation is simply 
\min_x ||Dx||_1 st Ax = b

When I run the program, I receive error:
```
Line: opt = op(sum(abs(D*x)), [A*x == b])
ArithmeticError: Rank(A) <p or Rank([G; A]) < n
```
What is interesting is that, when I implement the equivalent program in cvxpy, the minimization is correct. Is there something happening with D*x that I am not aware of?

**Comment by martinandersen** [comment]
By default the cvxopt solvers `conelp()` and `coneqp()` require the constraints to be linearly independent. cvxpy gets around this requirement by means of regularization (an undocumented cvxopt feature that only works with the LDL KKT solver). It is now possible (see dev branch 70e85816afb4440dea091de9cbe24b363972b3e0) to achieve the same in the cvxopt modeling module if you pass the following arguments to `solve()`:

```solve(kktsolver='ldl',options={'kktreg':1e-9})```
