### ISSUE TITLE
preserve commit history in branch master

### ISSUE THREAD

**Issue by johnyf** [cvxopt/cvxopt#74]
Looking at the history of branch `master`, it advances from release to release by one commit at a time (for example f3ca94fb997979a54b913f95b816132f7fd44820 to 8e16f3b44bc0c3fc3490d53336eb92c23735dd46). It is impossible in practice to keep track of the changes, without referring to branch `dev`.

However, any given project is understood to comprise of a graph with a single tip, not multiple. Therefore, it should be sufficient to look at branch `master` for one to observe and search the history. (It took me a long time--a few years--before I realized that history does exist in branch `dev`. I do not know of other projects that follow this approach on purpose.)

History is important, for several reasons, so it would be useful to preserve it, by rebasing `dev` onto `master` without squashing all commits into a single one between consecutive versions.

**Comment by martinandersen** [comment]
This is not intensional, and we're currently looking into how to proceed from where we are now. The problem is that we made a mistake when releasing 1.1.8. The dev branch (which was started after version 1.1.7) should have been rebased onto the master branch (preserving history) when we released 1.1.8, but instead a copy was added to the master branch. The situation is as follows:

```
master ----(1.1.7)-----------------(1.1.8)
                 \             
             dev  \----(A)----(B)----(C)----(D)----(E)----

(C) was copied to master and tagged 1.1.8
```

It may be too late to fix it, but we would like to avoid this kind of situation going forward. Ideally we would like the history to look as follows when we release 1.1.9:

```
master ----(1.1.7)----(A)----(B)----(1.1.8)----(D)----(E)----(1.1.9)
```

**Comment by johnyf** [comment]
Thank you for the information. It is generally not recommended to roll back branch `master`. In this case though, the latest commit is unintentional, so it could be regarded as correcting the situation.

A simple and explicit way to emphasize the rewriting of history is to create a branch `master_rewritten` (or other similar name), making it the repository's main branch, and delete branch `master` (`git push upstream :master`). This branch can remain in existence for some time (say a few months), so that people notice the change (strictly speaking, this does not violate the rule to not roll back history, because the branch was deleted).

After a long enough time, the branch `master` can be recreated (from `master_rewritten`), and the latter later deleted. Of course, rewriting `master` can happen at once, but it will confuse people.

Regarding rebasing, I would recommend incrementally invoking `git rebase`. Instead of one monolithic rebase, doing 15 gradual rebases is much more dependable, and raises fewer surprises (`git` gets less confused too). Moreover, aborting one of these small rebases does not throw away the effort invested into all the other rebases applied so far (because the previous rebases remain untouched). This is in contrast to monolithic rebasing, which can fail catastrophically at the last change, forcing an `--abort`.

A good way to check that no changes were lost overall is to keep an untouched remote (a temporary branch, or a branch in a private mirror repository), and always do a `git diff rebased_branch untouched_remote_branch` to ensure that the tips don't differ (i.e., that you didn't accidentally overwrite something, or accidentally omitted some commit). Worth noting that (locally) a rebase can always be undone via the [`reflog`](https://git-scm.com/docs/git-reflog).

After tidying history, preventing accidental rollbacks can be ensured by locking the branch `master_rewritten` on github.

Also, if you plan to use rebasing in future merges of `dev` into `master`, then you may find useful the commit message prefixes `fixup!` and `squash!`, and the associated option `git rebase --autosquash`. They are documented [here](https://git-scm.com/docs/git-rebase#_options), and [this](http://fle.github.io/git-tip-keep-your-branch-clean-with-fixup-and-autosquash.html) is an example. An overview for rebasing is given [here](https://help.github.com/articles/about-git-rebase/).

I would be happy to help, for example, by rebasing on a fork (from where you can pull a branch to here). Of course, I cannot know how you would prefer to rewrite history (if that was planned---I would definitely encourage doing so) of the `dev` branch, in order to produce the history of `master`, so the rebasing would be very simple, if not trivial.

**Comment by martinandersen** [comment]
Thanks for your thorough reply. The dev branch finally contains what we would like to turn into the next release of CVXOPT. If I create a new branch `master_rewritten` as you suggest, will previous releases and tags remain "intact"? 

Would it be easier to drop the dev commits between 1.1.7 and 1.1.8 and simply keep the history going forward? In other words, rebase (D) onto (1.1.8) as follows:

`master ----(1.1.7)----(1.1.8)----(D)----(E)----(1.1.9)`

**Comment by johnyf** [comment]
I agree that it is simpler (and conformant to standard practice) to not alter the existing history of `master`.

The previous tags would continue pointing at the existing commits, so you will effectively end up with a duplicate history in the github repository. Then, you would better recreate those tags, which isn't too bad, but is messier than worth it (we can imagine hundreds of people losing a few minutes each to figure out the same thing). So, the observation about tags is a very good one.

Taking this into consideration, I suggest moving on, making sure the same situation doesn't arise again. For the rebase that will produce v1.1.9, I would recommend the following:

```
master---(1.1.7)-----(1.1.8: corresponds to C)
                    |
                    | dev ------------(C)----(D)----(E)----(F)
```

1. start rebasing with incremental changes only, and without changing the base (i.e., just rewriting linear history). For example, `git rebase -i C --autosquash`, which will let you rewrite the tail `(D)----(E)----(F)` (but **not** `C`), and the result will be sitting on top of `C`. Confirm everything went as perceived with `git diff dev upstream/dev` throughout (letting `upstream/dev` untouched in the process).

2. when these changes are complete, take the resulting tale, say `(D)----(X)----(Y)----(Z)`, and move it onto master. Assuming that `(1.1.8)` is the tip of master, this can be done with `git rebase -i C --onto master`.

3. confirm the result is as desired `git diff master dev`. Inspect the resulting history in a GUI (e.g., `gitg` on Linux, `gitx` on a Mac, or by pushing to a github fork, or by `git checkout master; git checkout -b temp_master` and pushing to this repo `temp_master`).

4. `git push upstream master`

You may then want to `git push -f upstream dev` (perhaps keep the missing history by pushing the old `dev` to a branch called `old_dev`), and so essentially branch out from the most recent `master` for further development.

**Comment by martinandersen** [comment]
Thanks @johnyf for your help! I followed your suggestion and rebased the `dev` branch before merging with `master`. The old `dev` branch is now `old_dev`.
