### ISSUE TITLE
CVXOPT default solvers vs MESOK

### ISSUE THREAD

**Issue by jaredvacanti** [cvxopt/cvxopt#76]
I'm trying to solve a quadratic program to fit a cubic spline. I've had success in MATLAB but am not achieving the same results in Python with CVXOPT. 

Is there something (at a cursory level) that would make the results I achieve in MATLAB and the results I have in CVXOPT diverge? 

I can provide details and problem specification in python, but I am asking at a higher level. 

Much appreciated.

**Comment by martinandersen** [comment]
You should get the same result if both solvers succeed. CVXOPT actually allows you to solve your problem using MOSEK if both MOSEK and its Python extension are installed, so it should be easy to verify that the two solvers give the same result. 

Documentation: [Optional Solvers](http://cvxopt.org/userguide/coneprog.html?#optional-solvers)
