### ISSUE TITLE
Unable to compile under Ubuntu 13.04

### ISSUE THREAD

**Issue by jkrajniak** [cvxopt/cvxopt#8]
[teodor@lukrecja:cvxopt-1.1.6] $ python setup.py install --user
running install
running build
running build_py
running build_ext
building 'base' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/C/base.c -o build/temp.linux-x86_64-2.7/src/C/base.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/C/dense.c -o build/temp.linux-x86_64-2.7/src/C/dense.o
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c src/C/sparse.c -o build/temp.linux-x86_64-2.7/src/C/sparse.o
src/C/sparse.c: In function ‘sparse_concat’:
src/C/sparse.c:368:30: warning: variable ‘blk_ncols’ set but not used [-Wunused-but-set-variable]
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/C/base.o build/temp.linux-x86_64-2.7/src/C/dense.o build/temp.linux-x86_64-2.7/src/C/sparse.o -lm -llapack -lblas -o build/lib.linux-x86_64-2.7/cvxopt/base.so
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

[teodor@lukrecja:cvxopt-1.1.6] $ update-alternatives --config libblas.so.3
There is only one alternative in link group libblas.so.3 (providing /usr/lib/libblas.so.3): /usr/lib/libblas/libblas.so.3
Nothing to configure.

[teodor@lukrecja:cvxopt-1.1.6] $ update-alternatives --config liblapack.so.3
There is only one alternative in link group liblapack.so.3 (providing /usr/lib/liblapack.so.3): /usr/lib/lapack/liblapack.so.3
Nothing to configure.

**Comment by MyrionPhoenixmoon** [comment]
Shouldn't this at least go into the install instructions? Took me quite a bit of googling to find the reason why I can't install cvxpy/cvxopt on my Ubuntu 16.04.

**Comment by martinandersen** [comment]
It's already there: http://cvxopt.org/install/index.html
"The installation requires either ATLAS or BLAS + LAPACK. ... Both header files and libraries must be installed."

**Comment by MyrionPhoenixmoon** [comment]
I saw that, went ahead and installed libblas and liblapack, and was a bit frustrated because it still didn't work. I'm used to not needing the dev versions to install something. Perhaps it's obvious to you that the quoted sentence refers to the dev versions, but it wasn't obvious at all to me.

**Comment by martinandersen** [comment]
Thanks for the input — we'll try to improve the Ubuntu-specific instructions in the next release.

**Comment by MyrionPhoenixmoon** [comment]
Thank you!
