### ISSUE TITLE
option to fetch SuiteSparse sources automatically

### ISSUE THREAD

**Issue by johnyf** [cvxopt/cvxopt#80]
I definitely support the removal of SuiteSparse sources from the repository of `cvxopt`. Observing the reactions (#77, #78, #79), and not knowing whether some installation aid is already available, I would like to suggest providing a script for fetching SuiteSparse.

In more detail, I recommend an approach similar to what I've been doing in the package `dd`. This is a Python package that implements binary decision diagrams in both pure Python, as well as Cython bindings to various libraries, the most performant of which is [CUDD](http://vlsi.colorado.edu/~fabio/).

CUDD is not included in the distribution archive of `dd`, neither is it fetched automatically, because it is considered unexpected behavior for packages distributed via PyPI to silently download things from outside PyPI.

Nevertheless, this doesn't mean that a script cannot do the boring actions of fetching a compatible version of CUDD sources, checking the checksum, unpacking, placing it automatically at the right directory for linking, compiling it with the right flags, and then continuing with the Cython bindings etc.

The function that performs these actions is [download.py](https://github.com/johnyf/dd/blob/c6c2e62468957117972b443ae9aecf56c92c0fe6/download.py#L149), and it is [called from `setup.py`](https://github.com/johnyf/dd/blob/c6c2e62468957117972b443ae9aecf56c92c0fe6/setup.py#L80) if the option `--fetch` is passed to it.

The directive `--fetch` can be passed to `pip` too, as an `--install-option`. For now, this works as expected in `pip` requirements files, though it has a bug when used from the command line (https://github.com/pypa/pip/issues/1883).

**Comment by martinandersen** [comment]
This is a great suggestion. It would be even simpler in CVXOPT since it is not necessary to build SuiteSparse before running the setup script. Unfortunately, many people probably use pip directly (without a requirements file) so they would still have to download the SuiteSparse source if a shared library isn't available.

**Comment by johnyf** [comment]
Indeed, it is a small inconvenience to not be able to do this always via `pip`, but they can still do:

```shell
pip download cvxopt  # or git clone
tar -zxf cvxopt-*.tar.gz
cd cvxopt-*
python setup.py install --fetch
```

The automation will speed up things a little bit, and improve repeatability (plus the checksum validation).

**Comment by martinandersen** [comment]
I guess you can do more or less the same as follows:

```
wget http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-4.5.3.tar.gz
echo '2403007be38266e3607edfbf3833bee7f6bcb0f1  SuiteSparse-4.5.3.tar.gz' | shasum -c -
if [ $? -eq 0 ]; then
   tar -xf SuiteSparse-4.5.3.tar.gz
   CVXOPT_SUITESPARSE_SRC_DIR=$(pwd)/SuiteSparse pip install cvxopt
fi
```

**Comment by martinandersen** [comment]
We now have wheels for macOS and Linux, so I'm closing this issue.
