### ISSUE TITLE
Unlcear how the purpose of H matrix in cvxopt.solvers.cp

### ISSUE THREAD

**Issue by marekyggdrasil** [cvxopt/cvxopt#81]
I am having hard time understanding documentation for the non-linear optimization evaluation function `F` required by `cvxopt.solvers.cp`.

http://cvxopt.org/userguide/solvers.html#problems-with-nonlinear-objectives

Briefly, `H` matrix must constain sum of products of Laplacian operators and numbers `z`. This will obviously yield a number, however under which coordinates this result should be present in `H`? Unfortunately the example provided in the documentation doesn't reflect complicated case of multiple non-linear functions.

<img width="742" alt="nonlinear_convex_optimization_ _cvxopt_user_s_guide" src="https://cloud.githubusercontent.com/assets/8202674/21592424/b727d57a-d10d-11e6-8cbc-0881b5f3150b.png">

I will be very grateful for feedback and comments.

**Comment by martinandersen** [comment]
The matrix `H` is a conic combination (since z is positive) of the Hessians of f0,...,fm. Each Hessian matrix is a symmetric matrix of order n, and hence `H` is also a symmetric matrix of order n.

**Comment by marekyggdrasil** [comment]
This helped a lot and made it much more clear. Thank you!
