### ISSUE TITLE
Bad precision of conelp on many netlib-lp instances

### ISSUE THREAD

**Issue by sschnug** [cvxopt/cvxopt#83]
## Introduction
I'm trying to implement my own IPM-based LP-solver (without being an expert) and
during my first tests in regards to performance and robustness, i observed some
funny results of ```cvxopt's conelp solver```. *It seems that the precision is not competitive*.

### Instances
All netlib-lp instances [from here](http://www.netlib.org/lp/data/) without bounds (because my solver does not support bounds for now) excluding ```STOCFOR2``` (because incompatible with *gfortran*). ```Sum = 50```.

### Preprocessing
All instances are read by cvxopt's fromfile (MPS) and prepared with cvxopt's ```_inmatrixform```.

### SimpleIPM design
- Mehrotra-style using Augmented-system (no self-dual embedding)
- Umfpack in symmetric-mode
- A_ub -> A_eq through slacks (converting all original variables to free ones)
    - Anything better? 
- Variable-splitting for free-variables
    - No success yet with diagonal-regulization for doing this (in the augmented system)

#### Simple IPM
- stopping criterion: 1e-6

#### conelp
- defaults

#### Mosek 7
- defaults

### Filtering
Show only instances
- Which are correctly solved by SimpleIPM
- AND: Where conelp is not throwing an error (e.g. rank error or infeasiblity)

### Table

| SOLVER    |  25FV47            | ADLITTLE           | AGG2                | AGG3               | 
|-----------|--------------------|--------------------|---------------------|--------------------| 
| reference |  5501.8458883      | 225494.96316       | -20239252.356       | 10312115.935       | 
| SimpleIPM |  5501.845888428215 | 225494.96316258505 | -20239252.35597968  | 10312115.935089707 | 
| conelp    |  5501.846248953356 | 225494.96518310497 | -1.0                | -1.0               | 
| Mosek     |  5501.845888286745 | 225494.9631623804  | -20239252.355977114 | 10312115.935089223 | 

| SOLVER    |  BNL2               | ISRAEL             | SHARE1B            | SHIP04L            | 
|-----------|---------------------|--------------------|--------------------|--------------------| 
| reference |  1811.2365404       | -896644.82186      | -76589.318579      | 1793324.5380000004 | 
| SimpleIPM |  1811.2365404602606 | -896644.8218632042 | -76589.31857914478 | 1793324.5379705871 | 
| conelp    |  1811.2369084764082 | -896644.8152679397 | -76589.30532731244 | 1793324.5374621178 | 
| Mosek     |  1811.2365403585452 | -896644.8218630458 | -76589.31857918575 | 1793324.5379703557 | 

| SOLVER    |  SHIP04S            | SHIP08L            | SHIP08S            | SHIP12L            | 
|-----------|---------------------|--------------------|--------------------|--------------------| 
| reference |  1798714.7004       | 1909055.2114       | 1920098.2105       | 1470187.9193       | 
| SimpleIPM |  1798714.7004458453 | 1909055.2113900252 | 1920098.2105351489 | 1470187.9193295224 | 
| conelp    |  1798714.699875733  | 1909055.2054281826 | 1920098.1869885626 | 1470187.9146691468 | 
| Mosek     |  1798714.700445392  | 1909055.2113891316 | 1920098.21053462   | 1470187.9193292647 | 

| SOLVER    |  SHIP12S            | STOCFOR1            | STOCFOR2            | TRUSS              | 
|-----------|---------------------|---------------------|---------------------|--------------------| 
| reference |  1489236.1344       | -41131.976219       | -39024.408538       | 458815.84719       | 
| SimpleIPM |  1489236.1344065322 | -41131.976219201315 | -39024.408537698815 | 458815.8471857077  | 
| conelp    |  1489236.1338034715 | -41131.975295878416 | -39024.38725486912  | 458815.8469950348  | 
| Mosek     |  1489236.1344061291 | -41131.976219436416 | -39024.40853788202  | 458815.84718561673 | 

So the precision seems to be subpar and something is crashing completely with AGG2 + AGG3 (no error thrown).

There are other instances failing with rank-errors while the SimpleIPM is successful, but for now i just
printed the precision-values.

## Questions:
- These are not desired results, right?
- What's the source of this problem?
    - I thought, that conelp's default values of ```abstol```, ```reltol```,```feas``` should not allow results like this

Sascha

PS: I hope somebody can reproduce this, because my code is a bit too ugly for now to publish.

**Comment by martinandersen** [comment]
CVXOPT is not meant to compete with LP solvers like MOSEK. The returned results satisfy the default exit conditions, so there is nothing wrong. The default tolerances are not only used for LPs but for general cone LPs which are often more challenging numerically than LPs. You can (often) get more accurate results if you change the default tolerances.
