### ISSUE TITLE
The newest version (1.1.9) of cvxopt cannot be installed with glpk.

### ISSUE THREAD

**Issue by Edenharder** [cvxopt/cvxopt#84]
OS: Mac El Capitan
Python: 2.7.10
pip: pip 9.0.1

I can install the newest cvxopt with glpk, but when I test some code it tells me that
```
ValueError: invalid option (solver = 'glpk'): cvxopt.glpk is not installed
```

After all, I reinstall cvxopt 1.1.7 with glpk.

There is a [similar post in stackexchange](http://stackoverflow.com/questions/40312188/cvxopt-glpk-bindings-in-python?newreg=d8ebfd0fad814a209e07a31087edbe3e) with no answer currently.

**Comment by martinandersen** [comment]
Did you follow the steps outline in the [macOS installation instructions](http://cvxopt.org/install/index.html#macos)? If yes, make sure that you don't have multiple versions of CVXOPT installed on your system.

**Comment by Edenharder** [comment]
Yeah, I just followed the steps. And I have the same version of cvxopt installed both for the original python of the system and the one in Sagemath.

I can install cvxopt 1.1.7 with glpk smoothly, but not cvxopt 1.19 in the same steps.

**Comment by martinandersen** [comment]
CVXOPT 1.1.9 builds with GLPK and passes all tests on [Travis CI](https://travis-ci.org/cvxopt/cvxopt/jobs/180012925) so I guess there must be something different with your setup. Could you try checking `cvxopt.__version__` to make sure that the problem occurs with version 1.1.9? 

If you are using pip, a possible explanation could be that pip uses a [wheel cache](https://pip.pypa.io/en/stable/reference/pip_install/#wheel-cache). In this case, you could try reinstalling 1.1.9 with pip's `--no-cache-dir` option to ignore the cache and rebuild CVXOPT.

**Comment by Edenharder** [comment]
I think I have installed 1.1.9 with glpk successfully this time, both for the original Python of the system and the one in Sagemath. But I really don't know why. The other day, I tried many times without success.

Anyway, thanks very much!
