### ISSUE TITLE
cholmod not working with MKL since latest updates

### ISSUE THREAD

**Issue by gwaterst** [cvxopt/cvxopt#86]
Since the last version update, importing cholmod fails when cvxopt was linked against MKL.
Linking against MKL was done following the documentation at

    In [1]: import cvxopt
    
    In [2]: import cvxopt.cholmod
    --------------------------------------------------------------------------
    ImportError                              Traceback (most recent call last)
    <ipython-input-2-f423b6620ef6> in <module>()
    ----> 1 import cvxopt.cholmod
    
    ImportError: /home/hansmitdampf/Enthought/Canopy_64bit/bin/../lib/libgfortran.so.3: version `GFORTRAN_1.4' not found (required by /usr/lib/liblapack.so.3)

It seems like all other submoduls can be imported without errors.

**Comment by martinandersen** [comment]
The newest version of CVXOPT does work with MKL, but linking can be a bit tricky (I would recommend taking a look at Intel's [MKL Link Line Advisor](https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor) for more information). 

I assume that you are referring to CVXOPT version 1.1.9? What it the platform (some flavor of Linux I presume)? What version of Python? How did you install CVXOPT? Are you using a (precompiled) SuiteSparse shared library or are you building it from source along with CVXOPT?

**Comment by gwaterst** [comment]
I made it work!
I am using Arch Linux and rebuilt SuiteSparse from source, linking it to MKL.
Before, problems were nearly unsolvable because I had been using Canopy python, which makes it harder to compile and link packages appropriately.

Thank you four your help and support, problems were not related to CVXOPT itself.
