### ISSUE TITLE
trivial sdp example leads to dual infeasible

### ISSUE THREAD

**Issue by marekyggdrasil** [cvxopt/cvxopt#87]
Hello. I created a simple example of semidefinite program for which a trivial solution is 2 by 2 indentity matrix.

Here is a runnable example

```python
from copy import copy

from cvxopt import matrix, solvers
from cvxopt.lapack import syev

c = matrix([1.0, 0.0, -1.0])
G = [ matrix([[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]) ]
h = [ matrix([[0.0, 0.0], [0.0, 0.0]]) ]
sol = solvers.sdp(c, Gs=G, hs=h)

print "\nresulting matrix X"

X = matrix([[sol['x'][0], sol['x'][1]], [sol['x'][1], sol['x'][2]]])

WA = matrix(0.0, size = (1, 2), tc = 'd')
syev(copy(X), WA)

print X

print "eigenvalues of X"
print WA

WB = matrix(0.0, size = (1, 2), tc = 'd')
syev(copy(matrix([[1.0, 0.0], [0.0, 1.0]])), WA)

print "eigenvalues of 2x2 identity matrix"
print WB
```

Which outputs

```
$ python testsdp.py 
     pcost       dcost       gap    pres   dres   k/t
 0:  0.0000e+00 -0.0000e+00  4e+00  1e+00  2e+00  1e+00
 1: -3.9621e+01 -0.0000e+00  3e+02  2e+00  3e+00  4e+01
 2: -4.0211e+03 -0.0000e+00  3e+04  2e+00  3e+00  4e+03
 3: -4.0219e+05 -0.0000e+00  3e+06  2e+00  3e+00  4e+05
 4: -4.0219e+07 -0.0000e+00  3e+08  2e+00  3e+00  4e+07
Certificate of dual infeasibility found.

resulting matrix X
[-2.12e+00 -2.67e-20]
[-2.67e-20 -1.12e+00]

eigenvalues of X
[-2.12e+00 -1.12e+00]

eigenvalues of 2x2 identity matrix
[ 0.00e+00  0.00e+00]
```

If `x = [1.0, 0.0, 1.0` then solution would be an identity matrix with cost equal to `0.0` according to `c`.

2 by 2 identity matrix is positive semidefinite. Could someone who understands it better explain why this problem is `dual infeasible` and why while the `primal` is feasible why the final solution is NOT `positive semidefinite`? (both eigenvalues are negative)

**Comment by martinandersen** [comment]
If you look at the [documentation](http://cvxopt.org/userguide/coneprog.html#semidefinite-programming), you will see that the constraints are of the form `G*x + s == h` with `s` positive semidefinite. Here `x` is a vector. Thus, the problem that you are solving is equivalent to the following problem:

```
minimize    x[0] - x[2]
subject to  [ -x[0]  -x[1] ]  positive semidefinite
            [ -x[1]  -x[2] ] 
```

This implies that `0 >= x[0]` and  `0 >= x[2]`, and hence the primal is unbounded below and the dual is infeasible (let `x[1]=0`, `x[2] = 0`, and let `x[0]` go to neg. infinity).
