### ISSUE TITLE
fatal error: umfpack.h: No such file or directory

### ISSUE THREAD

**Issue by gdamirna** [cvxopt/cvxopt#88]
I have the problem and don't know how to fix. I am following this instruction for windows installantion [(http://cvxopt.org/install/index.html)]

When I try to execute this command:
python setup.py build --compiler=mingw32

I get this:

running build
running build_py
UPDATING build\lib.win-amd64-2.7\cvxopt/_version.py
set build\lib.win-amd64-2.7\cvxopt/_version.py to '1.1.9+1.gd8bd930'
running build_ext
building 'umfpack' extension
C:\Python27\Scripts\gcc.exe -mdll -O -Wall -I/usr/include/suitesparse -IC:\Python27\include -IC:\Python27\PC -c src/C/umfpack.c -o build\temp.win-amd64-2.7\Release\src\c\umfpack.o
src/C/umfpack.c:23:21: fatal error: umfpack.h: No such file or directory
#include "umfpack.h"
^
compilation terminated.
error: command 'C:\Python27\Scripts\gcc.exe' failed with exit status 1

Please, how can I solve this?

**Comment by martinandersen** [comment]
Did you download the SuiteSparse source and set the `CVXOPT_SUITESPARSE_SRC_DIR` environment variable?

**Comment by gdamirna** [comment]
I downloaded SuiteSparse from http://faculty.cse.tamu.edu/davis/suitesparse.html
And unzipped the file
How should I set CVXOPT_SUITESPARSE_SRC_DIR variable? What is the value of the variable?

**Comment by martinandersen** [comment]
It's in the [documentation](http://cvxopt.org/install/index.html#windows):
``` 
set CVXOPT_SUITESPARSE_SRC_DIR=c:\path\to\SuiteSparse
```
where `c:\path\to\SuiteSparse` should be the SuiteSparse source directory. You have to set these variables as well:

```
set CVXOPT_BLAS_LIB=openblaspy
set CVXOPT_LAPACK_LIB=openblaspy
set CVXOPT_BLAS_LIB_DIR=%CD%
set CVXOPT_BLAS_EXTRA_LINK_ARGS=-lgfortran;-lquadmath
```

Alternatively, you can try out our experimental precompiled binary wheel for Windows:

`pip install https://ci.appveyor.com/api/buildjobs/ayyv7jme1fgm95c9/artifacts/dist/cvxopt-1.1.9%2B4.ga9fa9fc-cp27-cp27m-win_amd64.whl`

**Comment by this38** [comment]
I have same issue but when deploying it to Cloud Foundry with a standard Python buildpack. Is there any help coming up?

Description:
I am unable to deploy CVXOPT package into Linux environment. I am on Python 3.6.0. and using standard python buildpacks (https://github.com/cloudfoundry/python-buildpack/releases) which I am trying to deploy on Clound Foundry for my IBM Bluemix app.

Are there any special buildpacks for this or CVXOPT cannot be working on Cloud Foundry? Thank you a lot!

`
2/14/2017 2:48:06 AM    OUT STG Running setup.py install for cvxopt: started

2/14/2017 2:48:20 AM    OUT STG Running setup.py install for cvxopt: finished with status 'error'

2/14/2017 2:48:20 AM    OUT STG Complete output from command /app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pgi7qybb/cvxopt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6vk81aol-record/install-record.txt --single-version-externally-managed --compile:

2/14/2017 2:48:20 AM    OUT STG running install

2/14/2017 2:48:20 AM    OUT STG running build

2/14/2017 2:48:20 AM    OUT STG creating build

2/14/2017 2:48:20 AM    OUT STG creating build/lib.linux-x86_64-3.5/cvxopt

2/14/2017 2:48:20 AM    OUT STG copying src/python/cvxprog.py -> build/lib.linux-x86_64-3.5/cvxopt

2/14/2017 2:48:20 AM    OUT STG copying src/python/__init__.py -> build/lib.linux-x86_64-3.5/cvxopt

2/14/2017 2:48:20 AM    OUT STG copying src/python/_version.py -> build/lib.linux-x86_64-3.5/cvxopt

2/14/2017 2:48:20 AM    OUT STG copying src/python/printing.py -> build/lib.linux-x86_64-3.5/cvxopt

2/14/2017 2:48:20 AM    OUT STG UPDATING build/lib.linux-x86_64-3.5/cvxopt/_version.py

2/14/2017 2:48:20 AM    OUT STG set build/lib.linux-x86_64-3.5/cvxopt/_version.py to '1.1.9'

2/14/2017 2:48:20 AM    OUT STG running build_ext

2/14/2017 2:48:20 AM    OUT STG building 'base' extension

2/14/2017 2:48:20 AM    OUT STG creating build/temp.linux-x86_64-3.5/src

2/14/2017 2:48:20 AM    OUT STG gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/app/.heroku/python/include/python3.5m -c src/C/dense.c -o build/temp.linux-x86_64-3.5/src/C/dense.o

2/14/2017 2:48:20 AM    OUT STG gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/app/.heroku/python/include/python3.5m -c src/C/sparse.c -o build/temp.linux-x86_64-3.5/src/C/sparse.o

2/14/2017 2:48:20 AM    OUT STG src/C/sparse.c: In function ‘sparse_concat’:

2/14/2017 2:48:20 AM    OUT STG src/C/sparse.c:368:30: warning: variable ‘blk_ncols’ set but not used [-Wunused-but-set-variable]

2/14/2017 2:48:20 AM    OUT STG int_t blk_nrows = 0, blk_ncols = 0;

2/14/2017 2:48:20 AM    OUT STG gcc -pthread -shared build/temp.linux-x86_64-3.5/src/C/base.o build/temp.linux-x86_64-3.5/src/C/dense.o build/temp.linux-x86_64-3.5/src/C/sparse.o -L/usr/lib -L/app/.heroku/vendor/lib -lm -llapack -lblas -lpython3.5m -o build/lib.linux-x86_64-3.5/cvxopt/base.cpython-35m-x86_64-linux-gnu.so

2/14/2017 2:48:20 AM    OUT STG gcc -pthread -shared build/temp.linux-x86_64-3.5/src/C/blas.o -L/usr/lib -L/app/.heroku/vendor/lib -lblas -lpython3.5m -o build/lib.linux-x86_64-3.5/cvxopt/blas.cpython-35m-x86_64-linux-gnu.so

2/14/2017 2:48:20 AM    OUT STG gcc -pthread -shared build/temp.linux-x86_64-3.5/src/C/lapack.o -L/usr/lib -L/app/.heroku/vendor/lib -llapack -lblas -lpython3.5m -o build/lib.linux-x86_64-3.5/cvxopt/lapack.cpython-35m-x86_64-linux-gnu.so

2/14/2017 2:48:20 AM    OUT STG src/C/umfpack.c:23:21: fatal error: umfpack.h: No such file or directory

2/14/2017 2:48:20 AM    OUT STG #include "umfpack.h"

2/14/2017 2:48:20 AM    OUT STG ^

2/14/2017 2:48:20 AM    OUT STG 

2/14/2017 2:48:20 AM    OUT STG ----------------------------------------

2/14/2017 2:48:21 AM    ERR STG Command "/app/.heroku/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pgi7qybb/cvxopt/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-6vk81aol-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-pgi7qybb/cvxopt/

2/14/2017 2:48:21 AM    ERR STG Failed to compile droplet

2/14/2017 2:48:21 AM    ERR STG Staging failed: Exited with status 223

2/14/2017 2:48:21 AM    OUT STG Destroying container
`

**Comment by martinandersen** [comment]
You may be able to use miniconda (see [Python Buildpack: Miniconda Support](http://docs.cloudfoundry.org/buildpacks/python/index.html#miniconda)) to install cvxopt via conda-forge:

```
conda install -c conda-forge cvxopt
```
