### ISSUE TITLE
How to change the maximal iteration in SDP and hide the progress of iterations?

### ISSUE THREAD

**Issue by Edenharder** [cvxopt/cvxopt#89]
The default number of iterations is 100, is it possible to change it to a larger number? By the way, it always print the whole progress of iterations, which is a long list. Is there anyway to hide this progress.

**Comment by martinandersen** [comment]
Yes, you can change the options dictionary (see [Algorithm Parameters](http://cvxopt.org/userguide/coneprog.html#algorithm-parameters)):

```
cvxopt.solvers.options['show_progress'] = False
cvxopt.solvers.options['maxiters'] = 200
