### ISSUE TITLE
 Rank(A) < p or Rank([G; A]) < n

### ISSUE THREAD

**Issue by gdamirna** [cvxopt/cvxopt#90]
I am trying to compute AC OPF using SOC constraint and some linear power flow constraints and when I try to solve my problem:

from cvxopt import matrix, spmatrix, solvers

c=matrix([10.,20.,0.,0.,0.,0.,0.,0.,0.])

G= [spmatrix ([-1.,-1.,-2.,-2.,-1.,1.],[0,0,1,2,3,3],[6,8,4,5,6,8])]

h= [matrix ([0.0,0.0,0.0,0.0]) ]

A= spmatrix ([0.66,0.74,-1.,1.,-0.2458,-1.,-1.,1.,-1.,-1.,1.],
             [0,0,0,0,0,1,1,1,2,2,2],
             [4,5,6,7,8,0,1,4,2,3,5],(3,9))

b=matrix([0.,-0.2,-0.3])

sol=solvers.socp(c,Gq=G, hq=h , A=A, b=b)

print(sol['x'])

I got this error:  
Traceback (most recent call last):
  File "C:/Python27/socp_dva_cvorista.py", line 16, in <module>
    sol=solvers.socp(c,Gq=G, hq=h , A=A, b=b)
  File "C:\Python27\lib\site-packages\cvxopt\coneprog.py", line 3529, in socp
    sol = conelp(c, G, h, dims, A = A, b = b, primalstart = ps, dualstart = ds, kktsolver = kktsolver, options = options)
  File "C:\Python27\lib\site-packages\cvxopt\coneprog.py", line 573, in conelp
    raise ValueError("Rank(A) < p or Rank([G; A]) < n")
ValueError: Rank(A) < p or Rank([G; A]) < n

Could anyone help me?
Thank you in advance

**Comment by martinandersen** [comment]
The problem is that you have redundant constraints (see [conelp documentation](http://cvxopt.org/userguide/coneprog.html#linear-cone-programs)). If is difficult to say how to fix this without a mathematical description of the problem that you are trying to solve.
