### ISSUE TITLE
Expressing a linear matrix inequality for a QCQP

### ISSUE THREAD

**Issue by MaximilianLomardo** [cvxopt/cvxopt#92]
Just very confused of how to formulate the problem of finding an optimal parameterized combination of symmetric matrices subject to the constraints that the parameters are greater than or equal to zero, and that the sum of the parameters is equal to 1.

Any tips/resources/examples available?

**Comment by martinandersen** [comment]
I suggest that you post a mathematical description of the problem that you want to solve in our [CVXOPT Google group](http://groups.google.com/forum/#!forum/cvxopt).
