### ISSUE TITLE
support for python 3.5+ in Windows

### ISSUE THREAD

**Issue by tsando** [cvxopt/cvxopt#94]
Hi, is there any timelines for when one will be able to install this in Windows using conda or pip install with python 3.5? I'm getting errors when I try to install it with python 3.5 and your documentation says you can only install it in Windows with python 3.4.

**Comment by martinandersen** [comment]
We are using [Mingwpy](https://mingwpy.github.io) to build Windows wheels on [AppVeyor](https://appveyor.com), and unfortunately Mingwpy currently does not support 3.5+. 

You can find some unofficial CVXOPT wheels for Windows here: 
http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by xoviat** [comment]
mingwpy has been abandoned. However, I can tell you how to to build if you tell me your C library dependencies.

**Comment by xoviat** [comment]
Particularly, if `libfftw3-dev` requires fortran, then you'll need to wait until flang is in conda-forge (conda-forge/staged-recipes#4360). But if not, I don't see any blocker.

**Comment by martinandersen** [comment]
The required libraries are BLAS, LAPACK, and SuiteSparse (DSDP, GSL, GLPK, and FFTW are optional). 

We currently build wheels for Windows on AppVeyor using mingwpy and without the optional extensions (see https://github.com/cvxopt/cvxopt/blob/master/.appveyor.yml).

**Comment by xoviat** [comment]
That's doable now. See here:

https://github.com/scikit-umfpack/scikit-umfpack-wheels/blob/master/appveyor.yml#L76

I looked at `setup.py`, and I would highly recommend switching to `numpy.distutils`, as it supports autoconfiguration (the C libraries are automatically detected rather than passing paths manually). If you have any further questions, let me know.

**Comment by martinandersen** [comment]
Thanks for the suggestion, I'll give it a shot. As far as I recall, our challenge with VS was the lack of support for C99 complex numbers (no complex.h, etc.). Do you know if the approach that you suggest requires a workaround for complex numbers?

**Comment by xoviat** [comment]
You can see the approach we took here: 

https://github.com/flang-compiler/flang/pull/288/files#diff-19be9b29886dd771324f1dd2107d734bR32

Basically the short version is that MSVC has "complex" types which are `_Dcomplex` and such. It also has complex functions which accept them. MSFT is not focused on resolving this issue because they want everyone to use C++.

**Comment by xoviat** [comment]
Though really the "ideal" solution is to use Cython because it solves the problem for you. I'm not sure how much time you might want to pour into that.

**Comment by martinandersen** [comment]
Thanks for point that out.

**Comment by martinandersen** [comment]
We will provide Windows x86-64 wheels with the next release of CVXOPT. 

In case anyone is interested in testing, you can download wheels for the most recent development version on [AppVeyor](https://ci.appveyor.com/project/martinandersen/cvxopt-wheels/history):
- [cvxopt-1.1.9+13.g4a684e5-cp27-cp27m-win_amd64.whl](https://ci.appveyor.com/api/buildjobs/d0gutjbw7rcncg91/artifacts/cvxopt%2Fdist%2Fcvxopt-1.1.9%2B13.g4a684e5-cp27-cp27m-win_amd64.whl)
- [cvxopt-1.1.9+13.g4a684e5-cp34-cp34m-win_amd64.whl](https://ci.appveyor.com/api/buildjobs/v7kn8w1j8uc69jhm/artifacts/cvxopt%2Fdist%2Fcvxopt-1.1.9%2B13.g4a684e5-cp34-cp34m-win_amd64.whl)
- [cvxopt-1.1.9+13.g4a684e5-cp35-cp35m-win_amd64.whl](https://ci.appveyor.com/api/buildjobs/6twb7qr4v7c4b9dd/artifacts/cvxopt%2Fdist%2Fcvxopt-1.1.9%2B13.g4a684e5-cp35-cp35m-win_amd64.whl)
- [cvxopt-1.1.9+13.g4a684e5-cp36-cp36m-win_amd64.whl](https://ci.appveyor.com/api/buildjobs/sf0g9ikomja05cqf/artifacts/cvxopt%2Fdist%2Fcvxopt-1.1.9%2B13.g4a684e5-cp36-cp36m-win_amd64.whl)
