### ISSUE TITLE
Cone QP Won't Terminate when matrices G and h are provided, fine with ONLY equality Ax=b

### ISSUE THREAD

**Issue by jaredvacanti** [cvxopt/cvxopt#96]
I have an ipython notebook here - complete with data so the example is completely reproducible.

https://gist.github.com/jaredvacanti/62010beda0ccfc20d2eac3c900858e50

Executed Block 17 very clear shows the issue here (the original values that are trying to be fit and the x vector I'm left with.

I have read on other portions of the mailing list that problems occur when h is not scaled properly? Is that possibly the case here?

The purpose of this quadratic programming problem is to fit a natural cubic spline, following the implementation of Green and Silverman (1994 - Nonparametric Regression and Generalized Linear Models), my vector x that I am optimizing for should consist of the observed knot values from 0 ... n-1 and the second derivatives at each point at n..2n-2.

When I only provide A  and b, the resulting vector x has a very good fit from the observed knot points. When I also add G and h, I get no optimal solution found with either MOSEK or the default CVXOPT solver. The conditions G and h are vital to the exercise, otherwise many other approaches would fit a generic spline with no boundary conditions.

Any ideas?

**Comment by martinandersen** [comment]
Closing the issue—the question has been posted here:
https://groups.google.com/forum/#!topic/cvxopt/tzyMweUB5LI
